# -*- encoding: utf-8 -*-
=begin
= 被ダメージ用セリフ設定（アクター用）

:dead_word ... 通常戦闘不能用セリフ
:orgasm_word ... 快楽戦闘不能用セリフ
:predation_word ... 捕食戦闘不能用セリフ
:incontinence_word ... 失禁用セリフ

==更新履歴
Date     Version Author Comment

=end

#==============================================================================
# ■ NWConst::Actor
#==============================================================================
module NWConst::Actor
  DOWN_WORDS = {
    1 => { # ルカ
      :dead_word => ["【ルカ】\nこんなところで、力尽きるなんて……", "ruka_fc1", 0],
      :orgasm_word => ["【ルカ】\nだめ、イっちゃうよぉ……\nあ、あぁぁぁぁ……！", "ruka_fc1", 0],
      :predation_word => ["【ルカ】\nいやだぁ、食べないでぇ……\nあ、あぁぁぁぁ……！", "ruka_fc1", 0],
      :incontinence_word => ["【ルカ】\n漏らしちゃうよぉ……\nあ、あぁぁぁぁ……！", "ruka_fc1", 0],
    },
    5 => { # アリス
      :dead_word => ["【アリス】\nぐっ、余がこんな……", "alice_fc5", 3],
      :orgasm_word => ["【アリス】\n余が、イかされてしまうなど……", "alice_fc5", 3],
      :predation_word => ["【アリス】\nた、食べるな……！\nうぁぁぁぁぁ！！", "alice_fc6", 0],
      :incontinence_word => ["【アリス】\n余が漏らすなど……\nあぁぁぁぁ……", "alice_fc6", 0],
    },
    12 => { # シルフ
      :dead_word => ["【シルフ】\nもうだめだよぉ……\nぐったり……", "sylph_fc1", 4],
      :orgasm_word => ["【シルフ】\nイっちゃうよぉ……\nはふぅぅぅ……", "sylph_fc1", 4],
      :predation_word => ["【シルフ】\nた、食べないでぇ……\nひゃぁぁぁん！", "sylph_fc1", 4],
      :incontinence_word => ["【シルフ】\nオモラシしちゃうよぉ……\nだめぇぇぇ……", "sylph_fc1", 4],
    },
    13 => { # ノーム
      :dead_word => ["【ノーム】\n……………………", "gnome_fc1", 1],
      :orgasm_word => ["【ノーム】\n…………～～！", "gnome_fc1", 1],
      :predation_word => ["【ノーム】\n……！！", "gnome_fc1", 1],
      :incontinence_word => ["【ノーム】\n……………………", "gnome_fc1", 1],
    },
    26 => { # イリアス
      :dead_word => ["【イリアス】\nなぜこの私が、こんな目に……", "iriasu_fc4", 4],
      :orgasm_word => ["【イリアス】\nこの私が、イってしまうなど……\nいや……あ、あぁぁぁ……", "iriasu_fc4", 6],
      :predation_word => ["【イリアス】\nい、いやです……たべないで……\nひゃぁぁぁぁ……！", "iriasu_fc4", 6],
      :incontinence_word => ["【イリアス】\nダメです、見ないで下さい……\nはぅぅぅぅぅ……", "iriasu_fc4", 6],
    },
    41 => { # プロメスティン
      :dead_word => ["【プロメスティン】\n意識が、遠のいて……", "stein_fc2", 2],
      :orgasm_word => ["【プロメスティン】\nこんな快感、はじめて……\nひゃぅぅぅん！", "stein_fc2", 2],
      :predation_word => ["【プロメスティン】\nや、やめて……食べないで……\nきゃぁぁぁぁ！", "stein_fc2", 2],
      :incontinence_word => ["【プロメスティン】\nこんな……漏らすところ、見られるなんて……\nはぅぅぅぅぅ……", "stein_fc2", 2],
    },
    53 => { # ライム
      :dead_word => ["【ライム】\nうにゅ～……", "slime_fc1", 2],
      :orgasm_word => ["【ライム】\nふにゃぁぁぁ……", "slime_fc1", 2],
      :predation_word => ["【ライム】\nたべられるの、やだ……\nひゃぁぁぁ……！", "slime_fc1", 2],
      :incontinence_word => ["【ライム】\nもらしちゃうよぉ……\nふぁぁぁぁ……", "slime_fc1", 2],
    },
    54 => { # うさ
      :dead_word => ["【うさ】\nきゅう……", "bunnyslime_fc1", 3],
      :orgasm_word => ["【うさ】\nイっちゃうよぉ……\nうにゅぅ……", "bunnyslime_fc1", 2],
      :predation_word => ["【うさ】\nあたし、おいしくないよ……\nただのスライムだから……ひゃぁぁぁ！", "bunnyslime_fc1", 3],
      :incontinence_word => ["【うさ】\nもれちゃう……\nうにゃぁぁぁ……", "bunnyslime_fc1", 2],
    },
    55 => { # メルク
      :dead_word => ["【メルク】\nネバネバ分が……足りないわ……", "name_fc1", 1],
      :orgasm_word => ["【メルク】\nああ、イっちゃう……", "name_fc1", 1],
      :predation_word => ["【メルク】\nやめて、食べないで……\nいやぁぁぁ……！", "name_fc1", 1],
      :incontinence_word => ["【メルク】\nああ、排出しちゃう……\nあぁぁぁぁ……", "name_fc1", 1],
    },
    56 => { # ラミ
      :dead_word => ["【ラミ】\nあたし、もうダメだよぉ……", "inp_fc1", 2],
      :orgasm_word => ["【ラミ】\nイっちゃうよぉ……\nはぅぅぅぅ……", "inp_fc1", 3],
      :predation_word => ["【ラミ】\nた、食べないで……ね？\nひゃぁぁぁぁん！", "inp_fc1", 2],
      :incontinence_word => ["【ラミ】\nオモラシしちゃうよぉ……\nふぇぇぇぇ……", "inp_fc1", 3],
    },
    57 => { # ルミ
      :dead_word => ["【ルミ】\nぐったり……", "inp_fc3", 2],
      :orgasm_word => ["【ルミ】\nだめ……", "inp_fc3", 2],
      :predation_word => ["【ルミ】\nやだ……", "inp_fc3", 2],
      :incontinence_word => ["【ルミ】\nもれる……", "inp_fc3", 2],
    },
    58 => { # レミ
      :dead_word => ["【レミ】\nぱたり……", "inp_fc2", 2],
      :orgasm_word => ["【レミ】\nびく……びくびくびくん！", "inp_fc2", 2],
      :predation_word => ["【レミ】\nびくびくびく……\n…………！！", "inp_fc2", 2],
      :incontinence_word => ["【レミ】\nだめ……だめぇ……", "inp_fc2", 2],
    },
    59 => { # ラゴラ
      :dead_word => ["【ラゴラ】\nもう無理だわ……", "mdg_fc1", 2],
      :orgasm_word => ["【ラゴラ】\nああ、イっちゃう……", "mdg_fc1", 2],
      :predation_word => ["【ラゴラ】\n食べるなら、頭の葉っぱだけにしてよぉ……\nいやぁぁぁぁ！！", "mdg_fc1", 2],
      :incontinence_word => ["【ラゴラ】\nも、漏らしちゃうなんて……\nあぁぁ……", "mdg_fc1", 2],
    },
    60 => { # ポチ
      :dead_word => ["【ポチ】\nきゃうん……", "dog_fc1", 4],
      :orgasm_word => ["【ポチ】\nほわわん……", "dog_fc1", 4],
      :predation_word => ["【ポチ】\nく～ん、食べないで……\n……きゃんきゃん！", "dog_fc1", 4],
      :incontinence_word => ["【ポチ】\nオモラシじゃないの、マーキングなのぉ……\nじょろろろろ……", "dog_fc1", 4],
    },
    61 => { # ミミー
      :dead_word => ["【ミミー】\nミミズは土に還るわ……", "mimizu_fc1", 2],
      :orgasm_word => ["【ミミー】\nイっちゃう……ミミズなのに……", "mimizu_fc1", 2],
      :predation_word => ["【ミミー】\nミミズを食べるなんて、ゲテモノ好きなの……！？\nきゃぁぁ！", "mimizu_fc1", 2],
      :incontinence_word => ["【ミミー】\nミミズが漏らすところなんて……\n見ないでよぉ……", "mimizu_fc1", 2],
    },
    62 => { # ゴブ
      :dead_word => ["【ゴブ】\nちょっと休ませてね……", "gob_fc1", 3],
      :orgasm_word => ["【ゴブ】\nこんなの……ダメになっちゃうよぉ……！", "gob_fc1", 3],
      :predation_word => ["【ゴブ】\nた、食べるなぁ……！\nやだぁぁぁぁ！！", "gob_fc1", 3],
      :incontinence_word => ["【ゴブ】\nオモラシとか……恥ずかしいよぉ……", "gob_fc1", 3],
    },
    64 => { # プチ
      :dead_word => ["【プチ】\nこんなぁ……きゅう……", "pramia_fc1", 2],
      :orgasm_word => ["【プチ】\n感じちゃうよぉ……ふぁぁぁ……", "pramia_fc1", 2],
      :predation_word => ["【プチ】\nあたし、おいしくないから！\nちょっと、聞いてる……？　きゃぁぁぁ！", "pramia_fc1", 2],
      :incontinence_word => ["【プチ】\nも、もらしちゃう……\nあぅぅぅ……", "pramia_fc1", 2],
    },
    66 => { # ヴァニラ
      :dead_word => ["【ヴァニラ】\n闇の世界を、覗き見してくるぞ……", "vgirl_fc1", 2],
      :orgasm_word => ["【ヴァニラ】\nだめ、イっちゃうぞ……\nひゃぅぅぅぅん……", "vgirl_fc1", 2],
      :predation_word => ["【ヴァニラ】\nた、食べるな……やめろ……！\nひゃぁぁぁ！", "vgirl_fc1", 2],
      :incontinence_word => ["【ヴァニラ】\nまた、オモラシしちゃったぞ……", "vgirl_fc1", 2],
    },
    68 => { # パピ
      :dead_word => ["【パピ】\nうがが……", "dragonp_fc1", 2],
      :orgasm_word => ["【パピ】\nなんなのだ、これ……？\nからだが……はぅぅぅ～～！", "dragonp_fc1", 2],
      :predation_word => ["【パピ】\nた、食べるな！　胃の中で噛み付くぞ……！\nひゃぁぁぁぁぁ！！", "dragonp_fc1", 2],
      :incontinence_word => ["【パピ】\nパンツ、濡らしちゃったぞ……", "dragonp_fc1", 2],
    },
    70 => { # ラティ
      :dead_word => ["【ラティ】\nあたし、もうダメ……", "nezumi_fc1", 2],
      :orgasm_word => ["【ラティ】\nい、イっちゃうよぉ～！", "nezumi_fc1", 2],
      :predation_word => ["【ラティ】\nた、食べちゃダメ……\nやぁぁぁぁ！！", "nezumi_fc1", 2],
      :incontinence_word => ["【ラティ】\nおもらし……見ないで……\nふぁぁぁぁ……", "nezumi_fc1", 2],
    },
    71 => { # アマラ
      :dead_word => ["【アマラ】\nうが……ご先祖様が、呼んでるぞ……", "okami_fc1", 2],
      :orgasm_word => ["【アマラ】\nうが……頭の中が真っ白になるぞ……", "okami_fc1", 2],
      :predation_word => ["【アマラ】\nあたしが、食べられるなんて……\nいやぁぁぁ……！！", "okami_fc1", 2],
      :incontinence_word => ["【アマラ】\nこんなところで、漏らしちゃうなんて……", "okami_fc1", 2],
    },
    72 => { # ミニ
      :dead_word => ["【ミニ】\nやられちゃったぞー！", "phoenix_fc1", 2],
      :orgasm_word => ["【ミニ】\nこんなの、初めてだぞ……\nひゃぅぅ……", "phoenix_fc1", 5],
      :predation_word => ["【ミニ】\nフェニックス食べたらヤケドするぞ……！\nひゃぁぁぁぁ！！", "phoenix_fc1", 2],
      :incontinence_word => ["【ミニ】\nオモラシなんて、卒業したんだぞ……\nでも、もれちゃう……", "phoenix_fc1", 5],
    },
    73 => { # ヒル
      :dead_word => ["【ヒル】\nそ、そんな……！", "hiru_fc1", 2],
      :orgasm_word => ["【ヒル】\n私、がイかされるなんて……", "hiru_fc1", 2],
      :predation_word => ["【ヒル】\n私が食べられるの……？\nあ、あぁぁぁぁ……！", "hiru_fc1", 2],
      :incontinence_word => ["【ヒル】\n私が体液を垂れ流すなんて……\nあぁぁぁ……", "hiru_fc1", 2],
    },
    74 => { # バーニー
      :dead_word => ["【バーニー】\nくっ、不覚を取ったわね……", "usagi_fc1", 2],
      :orgasm_word => ["【バーニー】\nみんなの前で、イかされちゃうなんて……", "usagi_fc1", 2],
      :predation_word => ["【バーニー】\nた、食べないで……お姉さん、何でもするから……\nきゃぁぁぁぁ！！", "usagi_fc1", 2],
      :incontinence_word => ["【バーニー】\nも、漏らしちゃうなんて、恥ずかしい……", "usagi_fc1", 2],
    },
    75 => { # メリー
      :dead_word => ["【メリー】\n川の向こうで、ヒツジおばあちゃんが手を振ってるのら……", "hituzi_fc1", 3],
      :orgasm_word => ["【メリー】\nよっぱらいにイタズラするなんて、らめなのらぁ～", "hituzi_fc1", 3],
      :predation_word => ["【メリー】\nあたしを食べると、肝臓に悪いのら……", "hituzi_fc1", 3],
      :incontinence_word => ["【メリー】\n漏らしちゃうのら……\nよっぱらいだから許して……", "hituzi_fc1", 3],
    },
    76 => { # シュリー
      :dead_word => ["【シュリー】\nもう動けないよぉ……", "syuree_fc1", 2],
      :orgasm_word => ["【シュリー】\nなにこれ、気持ちいいよぉ……", "syuree_fc1", 3],
      :predation_word => ["【シュリー】\nあたしって、オイシイのぉ？\n感想、聞かせてね……", "syuree_fc1", 1],
      :incontinence_word => ["【シュリー】\n漏らしちゃうよぉ……\nじょろろろろ……", "syuree_fc1", 3],
    },
    77 => { # ジェイド
      :dead_word => ["【ジェイド】\n機能停止、シャットオフ……", "jeid_fc1", 2],
      :orgasm_word => ["【ジェイド】\n快楽メーター、マックス……", "jeid_fc1", 3],
      :predation_word => ["【ジェイド】\n危険度最大……捕食されます……", "jeid_fc1", 2],
      :incontinence_word => ["【ジェイド】\nオイル排出……\nいや、これはオイルではなく……", "jeid_fc1", 3],
    },
    78 => { # シェスタ
      :dead_word => ["【シェスタ】\nああ、神様……", "syesta_fc1", 2],
      :orgasm_word => ["【シェスタ】\n気持ちいい、いっちゃう……", "syesta_fc1", 2],
      :predation_word => ["【シェスタ】\n私が、食べられる……？", "syesta_fc1", 2],
      :incontinence_word => ["【シェスタ】\n私が、漏らすの……？", "syesta_fc1", 2],
    },
    79 => { # ヌルコ
      :dead_word => ["【ヌルコ】\nきゅ……", "nuruko_fc1", 2],
      :orgasm_word => ["【ヌルコ】\nきゅ～～", "nuruko_fc1", 2],
      :predation_word => ["【ヌルコ】\n……きゅ！！", "nuruko_fc1", 2],
      :incontinence_word => ["【ヌルコ】\nきゅきゅ……", "nuruko_fc1", 2],
    },
    80 => { # ヒップ
      :dead_word => ["【ヒップ】\nぶひぃ……", "orc_fc1", 2],
      :orgasm_word => ["【ヒップ】\nオークなのに……\nオークなのにぃ……", "orc_fc1", 2],
      :predation_word => ["【ヒップ】\nぶひぃ、あたしは美味しくないです！\nおいしそうですけど、おいしくないです……", "orc_fc1", 2],
      :incontinence_word => ["【ヒップ】\nぶひ……オークなのに、こんな屈辱……", "orc_fc1", 2],
    },
    81 => { # ハニー
      :dead_word => ["【ハニー】\nハチミツ舐めて、休憩するわ……", "mitubati_fc1", 2],
      :orgasm_word => ["【ハニー】\nこんなの、イかされちゃうわ……", "mitubati_fc1", 2],
      :predation_word => ["【ハニー】\nあたし、甘くて美味しいと思ってる？\nたぶん正解だけど、やめてぇ……！", "mitubati_fc1", 2],
      :incontinence_word => ["【ハニー】\nああ、漏らしちゃうわ……", "mitubati_fc1", 2],
    },
    82 => { # ちゅん
      :dead_word => ["【ちゅん】\nどうせあたし、弱いですし……", "suzume_fc1", 3],
      :orgasm_word => ["【ちゅん】\nダメです、イっちゃいます……", "suzume_fc1", 3],
      :predation_word => ["【ちゅん】\n食べられちゃうんですか、あたし……", "suzume_fc1", 3],
      :incontinence_word => ["【ちゅん】\nこんなの、恥ずかしいです……", "suzume_fc1", 3],
    },
    83 => { # レイナ
      :dead_word => ["【レイナ】\nかわしきれなかったよぉ……", "hapy_a_fc1", 2],
      :orgasm_word => ["【レイナ】\nイっちゃう、きもちいいよぉ……", "hapy_a_fc1", 2],
      :predation_word => ["【レイナ】\nた、食べないでぇ……\nあぁぁぁぁ！", "hapy_a_fc1", 2],
      :incontinence_word => ["【レイナ】\nやだぁ、漏れちゃうよぉ……", "hapy_a_fc1", 2],
    },
    84 => { # ピナ＆ピィ
      :dead_word => ["【ピナ＆ピィ】\nお姉ちゃん、もうダメだよぉ……", "hapy_bc_fc1", 2],
      :orgasm_word => ["【ピナ＆ピィ】\nお姉ちゃん、イかされちゃうよぉ……", "hapy_bc_fc1", 2],
      :predation_word => ["【ピナ＆ピィ】\nお姉ちゃん、食べられちゃうよぉ……", "hapy_bc_fc1", 2],
      :incontinence_word => ["【ピナ＆ピィ】\n妹の前で、オモラシしちゃうなんて……", "hapy_bc_fc1", 2],
    },
    85 => { # エリザベス
      :dead_word => ["【エリザベス】\nく、くやしい……この私が……！", "highslag_fc1", 2],
      :orgasm_word => ["【エリザベス】\n私がイかされるなんて……くやしい……！", "highslag_fc1", 2],
      :predation_word => ["【エリザベス】\nわ、私が食べられるなんて……！", "highslag_fc1", 2],
      :incontinence_word => ["【エリザベス】\nわ、私が人前で漏らすなんて……", "highslag_fc1", 2],
    },
    86 => { # ロザリオ
      :dead_word => ["【ロザリオ】\n神よ、少し休みます……", "name_s_fc1", 2],
      :orgasm_word => ["【ロザリオ】\nああ、このような快感が……\nあぁぁぁぁ……！", "name_s_fc1", 2],
      :predation_word => ["【ロザリオ】\nああ神よ、助けて……\nあ、あぁぁぁぁ……！", "name_s_fc1", 2],
      :incontinence_word => ["【ロザリオ】\nああ、このような屈辱……\nあぁぁぁぁ……", "name_s_fc1", 2],
    },
    87 => { # メルティ
      :dead_word => ["【メルティ】\n私達が、かなわないなんて……", "name2_fc2", 3],
      :orgasm_word => ["【メルティ】\n私達が、イかされるなんて……", "name2_fc2", 3],
      :predation_word => ["【メルティ】\nた、食べないで……あぁぁぁ！", "name2_fc2", 3],
      :incontinence_word => ["【メルティ】\nああ、漏らしちゃう……", "name2_fc2", 3],
    },
    88 => { # かぼちゃ
      :dead_word => ["【かぼちゃ】\nかぼちゃ、こわれちゃった……", "jack_fc1", 2],
      :orgasm_word => ["【かぼちゃ】\nおまたが……変なの……", "jack_fc1", 2],
      :predation_word => ["【かぼちゃ】\nあたし、かぼちゃの味しかしないよ……", "jack_fc1", 2],
      :incontinence_word => ["【かぼちゃ】\nオモラシしちゃう……", "jack_fc1", 2],
    },
    89 => { # シンディ
      :dead_word => ["【シンディ】\nお腹が減ったわね……", "ropa_fc1", 2],
      :orgasm_word => ["【シンディ】\nこんな……イかされるなんて……", "ropa_fc1", 2],
      :predation_word => ["【シンディ】\nあたし、食べられるの……？", "ropa_fc1", 2],
      :incontinence_word => ["【シンディ】\n漏らすなんて……見ないでよ……", "ropa_fc1", 2],
    },
    90 => { # メルメル
      :dead_word => ["【メルメル】\nかさかさ……ぱたり。", "meda_fc1", 0],
      :orgasm_word => ["【メルメル】\nびくびく、びくん……", "meda_fc1", 0],
      :predation_word => ["【メルメル】\nじたばた、もぞもぞ……", "meda_fc1", 0],
      :incontinence_word => ["【メルメル】\nぶるぶる、ぶるっ……", "meda_fc1", 0],
    },
    91 => { # キャンドラ
      :dead_word => ["【キャンドラ】\nこの火も消えてしまうのね……", "candle_fc1", 2],
      :orgasm_word => ["【キャンドラ】\n最期に、こんな快楽が味わえるなんて……", "candle_fc1", 2],
      :predation_word => ["【キャンドラ】\n他者の糧となって、生を終えるのね……", "candle_fc1", 2],
      :incontinence_word => ["【キャンドラ】\nこんなの……ロウが漏れ出してしまうわ……", "candle_fc1", 2],
    },
    92 => { # イーター
      :dead_word => ["【イーター】\n食べたい……食べたい……", "eater_fc1", 2],
      :orgasm_word => ["【イーター】\n体、おかしい……", "eater_fc1", 1],
      :predation_word => ["【イーター】\n食べられるの、やだ……\n食べたい……", "eater_fc1", 4],
      :incontinence_word => ["【イーター】\n漏れる……", "eater_fc1", 1],
    },
    93 => { # ライオット
      :dead_word => ["【ライオット】\nぐっ、もう無理か……", "liot_fc1", 2],
      :orgasm_word => ["【ライオット】\nだ、だめ……感じすぎて……", "liot_fc1", 3],
      :predation_word => ["【ライオット】\nここで餌食となるか……", "liot_fc1", 2],
      :incontinence_word => ["【ライオット】\nこんな、私が……惨めだ……", "liot_fc1", 3],
    },
    94 => { # ルクスル
      :dead_word => ["【ルクスル】\n戦闘続行不能……体が、動かな……", "luksl_fc1", 2],
      :orgasm_word => ["【ルクスル】\nあははっ、イかせてくれるのぉ……！？", "luksl_fc1", 1],
      :predation_word => ["【ルクスル】\n私は胃にもたれるわ、心しなさいよねぇ！", "luksl_fc1", 2],
      :incontinence_word => ["【ルクスル】\nあははっ、漏れちゃうわぁ……！", "luksl_fc1", 1],
    },
    95 => { # ロナ
      :dead_word => ["【ロナ】\nくっ、私が負けるなんて……", "delh_a_fc1", 2],
      :orgasm_word => ["【ロナ】\nだ、だめ……イっちゃう～！", "delh_a_fc1", 2],
      :predation_word => ["【ロナ】\nた、食べないで……やめて……\nあぁぁぁぁ……！！", "delh_a_fc1", 2],
      :incontinence_word => ["【ロナ】\nだめ、漏れちゃう……\nやめてぇ、見ないでぇ……", "delh_a_fc1", 2],
    },
    96 => { # マリオン
      :dead_word => ["【マリオン】\nこれ以上は、もう無理ね……", "delh_b_fc1", 2],
      :orgasm_word => ["【マリオン】\nこの私が、イかされるなんて……", "delh_b_fc1", 2],
      :predation_word => ["【マリオン】\n私が食べられるなんて、そんな……", "delh_b_fc1", 2],
      :incontinence_word => ["【マリオン】\nああ、こんな屈辱……", "delh_b_fc1", 2],
    },
    97 => { # フェル
      :dead_word => ["【フェル】\nうわ～", "fairy_fc1", 2],
      :orgasm_word => ["【フェル】\nイっちゃうよぉ～", "fairy_fc1", 2],
      :predation_word => ["【フェル】\nいやぁ……食べないでぇ……", "fairy_fc1", 2],
      :incontinence_word => ["【フェル】\nオモラシしちゃうよぉ……", "fairy_fc1", 2],
    },
    98 => { # エイミ
      :dead_word => ["【エイミ】\nうわ～ん！", "minikani_fc1", 2],
      :orgasm_word => ["【エイミ】\nイっちゃうところ、見ないで～！", "minikani_fc1", 2],
      :predation_word => ["【エイミ】\nわ～ん、食べないで～！", "minikani_fc1", 2],
      :incontinence_word => ["【エイミ】\nオモラシするところ、見ないで～！", "minikani_fc1", 2],
    },
    99 => { # ギギ
      :dead_word => ["【ギギ】\nおのれ、年寄りをいじめるとは……", "namazu_fc1", 2],
      :orgasm_word => ["【ギギ】\nこの儂を、辱めおって……はぅぅぅ。", "namazu_fc1", 2],
      :predation_word => ["【ギギ】\nおい、儂の肉は不味いぞ……！\nひゃぁぁぁぁ！！", "namazu_fc1", 2],
      :incontinence_word => ["【ギギ】\nこの儂が、人前で失禁してしまうとは……", "namazu_fc1", 2],
    },
    100 => { # フレシア
      :dead_word => ["【フレシア】\nそんな……私が……", "rahure_fc1", 2],
      :orgasm_word => ["【フレシア】\nああ、気持ちいい……", "rahure_fc1", 2],
      :predation_word => ["【フレシア】\n食べるなら、花びらだけにして……\nあ、あぁぁぁ……！", "rahure_fc1", 2],
      :incontinence_word => ["【フレシア】\nどっぷりと漏れちゃう……\nきっと、すごい匂い……", "rahure_fc1", 2],
    },
    101 => { # リヒティーヌ
      :dead_word => ["【リヒティーヌ】\n走りだけじゃ、どうにもならないか……", "cent2_fc1", 2],
      :orgasm_word => ["【リヒティーヌ】\nああ、みんなの前でイかされちゃう……", "cent2_fc1", 2],
      :predation_word => ["【リヒティーヌ】\nお願い、食べないでぇ……\nきゃぁぁぁぁ！", "cent2_fc1", 2],
      :incontinence_word => ["【リヒティーヌ】\nああ、みんなの前で漏らしちゃう……", "cent2_fc1", 2],
    },
    102 => { # きつね
      :dead_word => ["【きつね】\nひゃぁぁぁぁ……！", "youko_fc1", 2],
      :orgasm_word => ["【きつね】\nひゃぁぁ、気持ちいいよぉ……", "youko_fc1", 2],
      :predation_word => ["【きつね】\n食べないで、あぶらあげあげるから……\nひゃぁぁぁぁ！", "youko_fc1", 2],
      :incontinence_word => ["【きつね】\nオモラシしちゃうよぉ……\nうぇ～ん……", "youko_fc1", 2],
    },
    103 => { # かむろ
      :dead_word => ["【かむろ】\n駄目です、少し休みます……", "kamuro_fc1", 2],
      :orgasm_word => ["【かむろ】\nこ、こんなのぉ……はぅぅぅ……", "kamuro_fc1", 2],
      :predation_word => ["【かむろ】\nた、食べられるのやだ……\nあぁぁぁぁ……", "kamuro_fc1", 2],
      :incontinence_word => ["【かむろ】\nごめんなさい、オモラシしちゃいます……\nはぅぅ……ごめん、なさい……", "kamuro_fc1", 2],
    },
    104 => { # ラクネ
      :dead_word => ["【ラクネ】\nそんな、私がやられるなんて……！", "kumo_fc1", 2],
      :orgasm_word => ["【ラクネ】\nイかされるなんて……屈辱……！", "kumo_fc1", 2],
      :predation_word => ["【ラクネ】\n食べられるの？　嘘でしょ、この私が……？", "kumo_fc1", 2],
      :incontinence_word => ["【ラクネ】\nも、漏れちゃう……はぅぅぅ……", "kumo_fc1", 2],
    },
    105 => { # ミネリ
      :dead_word => ["【ミネリ】\nひ、ひどい……！", "mimic_fc1", 1],
      :orgasm_word => ["【ミネリ】\nやだ、だめぇ……", "mimic_fc1", 1],
      :predation_word => ["【ミネリ】\nた、食べないで！\nお願い、何でもするからぁ……きゃぁぁ！", "mimic_fc1", 1],
      :incontinence_word => ["【ミネリ】\nも、漏らしちゃう……\n箱の中なら、いいよね……", "mimic_fc1", 1],
    },
    106 => { # 七尾
      :dead_word => ["【七尾】\nくっ、不覚を取りましたか……", "nanabi_fc1", 3],
      :orgasm_word => ["【七尾】\nこの私が、なんたる屈辱……", "nanabi_fc1", 3],
      :predation_word => ["【七尾】\nこの七尾、他者の餌食になるとは……！", "nanabi_fc1", 3],
      :incontinence_word => ["【七尾】\nわ、私が漏らすなんて……\nみ、見ないで下さい……", "nanabi_fc1", 3],
    },
    107 => { # ユメ
      :dead_word => ["【ユメ】\nこんな、まさか……", "namako_fc1", 2],
      :orgasm_word => ["【ユメ】\n気持ちいいけど、恥ずかしいわ……", "namako_fc1", 2],
      :predation_word => ["【ユメ】\nゲテモノ食いなんて、感心しない……\nきゃぁぁぁぁ！", "namako_fc1", 2],
      :incontinence_word => ["【ユメ】\n漏らしちゃうわ……あぁぁ……", "namako_fc1", 2],
    },
    108 => { # シェリー
      :dead_word => ["【シェリー】\nああ、こんな乱暴な……", "kai_fc1", 2],
      :orgasm_word => ["【シェリー】\n旦那様以外の方に、イかされてしまうなんて……", "kai_fc1", 2],
      :predation_word => ["【シェリー】\nどうか、食べないで……\nあぁぁぁぁ……！", "kai_fc1", 2],
      :incontinence_word => ["【シェリー】\n旦那様、こんな私の姿を見ないで……", "kai_fc1", 2],
    },
    109 => { # ソープ
      :dead_word => ["【ソープ】\nこんなの、やだよぉ……", "kani_fc1", 2],
      :orgasm_word => ["【ソープ】\n気持ちいいの、クセになっちゃうよぉ……", "kani_fc1", 2],
      :predation_word => ["【ソープ】\nた、食べないで……！\nやだ……あぁぁぁ！", "kani_fc1", 2],
      :incontinence_word => ["【ソープ】\nひ、人前でオシッコ漏らすなんて……\nやぁぁぁ……", "kani_fc1", 2],
    },
    110 => { # ベス
      :dead_word => ["【ベス】\nなんで、あたしがこんな目に合うのぉ……", "slimelord_fc1", 2],
      :orgasm_word => ["【ベス】\nぷるぷる、イっちゃうよぉ……", "slimelord_fc1", 2],
      :predation_word => ["【ベス】\n食べないで、食べないでよぉ……", "slimelord_fc1", 2],
      :incontinence_word => ["【ベス】\nもれちゃう、もれちゃうよぉ……", "slimelord_fc1", 2],
    },
    111 => { # メロン
      :dead_word => ["【メロン】\nあたしのスイカ、割れちゃった……", "suika_fc1", 2],
      :orgasm_word => ["【メロン】\nこんなの、悔しい……", "suika_fc1", 2],
      :predation_word => ["【メロン】\n食べるのならスイカだけにして！\n私は……あぁぁぁ！", "suika_fc1", 2],
      :incontinence_word => ["【メロン】\n漏らすところなんか、見ないでよぉ……", "suika_fc1", 2],
    },
    112 => { # かずら
      :dead_word => ["【かずら】\nあたしがやられちゃうなんて……", "utubo_fc1", 2],
      :orgasm_word => ["【かずら】\nこんなの、気持ち良すぎて……", "utubo_fc1", 2],
      :predation_word => ["【かずら】\nあたしが逆に食べられるなんて……\nせめて、気持ち良く溶かして……", "utubo_fc1", 2],
      :incontinence_word => ["【かずら】\n漏らしちゃうなんて……\n消化液まで漏れちゃう……", "utubo_fc1", 2],
    },
    113 => { # アナスタシア
      :dead_word => ["【アナスタシア】\nそんな……この私が……", "lamia_fc1", 2],
      :orgasm_word => ["【アナスタシア】\nこの私が、イかされるなんて……", "lamia_fc1", 2],
      :predation_word => ["【アナスタシア】\nこの私が食べられるの……？\nそんな……あぁぁぁぁ！", "lamia_fc1", 2],
      :incontinence_word => ["【アナスタシア】\nダメ、漏らしちゃう……\nあぁぁぁぁ……！", "lamia_fc1", 2],
    },
    114 => { # わかめ
      :dead_word => ["【わかめ】\nゆらり……ぱたん。", "wakame_fc1", 2],
      :orgasm_word => ["【わかめ】\nんんっ……ゆらゆらゆら……", "wakame_fc1", 2],
      :predation_word => ["【わかめ】\nあたし、美味しくないから……\nうそ、たぶん美味しいと思う……", "wakame_fc1", 2],
      :incontinence_word => ["【わかめ】\nゆらゆら……漏れちゃう……", "wakame_fc1", 2],
    },
    115 => { # くらげ
      :dead_word => ["【くらげ】\nもうだめ……", "kurage_fc1", 0],
      :orgasm_word => ["【くらげ】\nきもちいい……", "kurage_fc1", 0],
      :predation_word => ["【くらげ】\nたべないで……", "kurage_fc1", 0],
      :incontinence_word => ["【くらげ】\nもらしちゃった……", "kurage_fc1", 0],
    },
    116 => { # イザベル
      :dead_word => ["【イザベル】\nきゃぁぁぁ……！", "iso_fc1", 2],
      :orgasm_word => ["【イザベル】\n私がイかされるなんてぇ……！", "iso_fc1", 2],
      :predation_word => ["【イザベル】\n私を食べるなんて、ただじゃおかないわ……！\nやだ、あぁぁぁぁ……！", "iso_fc1", 2],
      :incontinence_word => ["【イザベル】\nくっ、私が漏らすなんて……\nだめ、あぁぁ……", "iso_fc1", 2],
    },
    117 => { # あんこ
      :dead_word => ["【あんこ】\n……………………", "ankou_fc1", 0],
      :orgasm_word => ["【あんこ】\n……………………", "ankou_fc1", 0],
      :predation_word => ["【あんこ】\n……………………", "ankou_fc1", 0],
      :incontinence_word => ["【あんこ】\n……………………", "ankou_fc1", 0],
    },
    118 => { # メイア
      :dead_word => ["【メイア】\nああ、こんな事って……", "meia_fc1", 3],
      :orgasm_word => ["【メイア】\n気持ちいい……\nでも、惨めです……", "meia_fc1", 3],
      :predation_word => ["【メイア】\nた、食べないで……きゃぁぁぁ！", "meia_fc1", 3],
      :incontinence_word => ["【メイア】\nひ、人前で漏らしてしまうなんて……\n恥ずかしいです……", "meia_fc1", 3],
    },
    119 => { # アニー
      :dead_word => ["【アニー】\n体が動かない……", "page17_fc1", 0],
      :orgasm_word => ["【アニー】\nこんな感覚……ん、んんん……", "page17_fc1", 0],
      :predation_word => ["【アニー】\n私が食べられるなんて……", "page17_fc1", 0],
      :incontinence_word => ["【アニー】\n私が漏らすなんて……", "page17_fc1", 0],
    },
    120 => { # ヨーコ
      :dead_word => ["【ヨーコ】\n少し休ませてもらいましょう……", "page257_fc1", 2],
      :orgasm_word => ["【ヨーコ】\nああ、こんな快感……\n私、もうダメです……", "page257_fc1", 2],
      :predation_word => ["【ヨーコ】\nた、食べないで……\nこんな、いや……あぁぁぁ……！", "page257_fc1", 2],
      :incontinence_word => ["【ヨーコ】\nこんな、恥ずかしい……\n見ないで、ください……", "page257_fc1", 2],
    },
    121 => { # コーネリア
      :dead_word => ["【コーネリア】\nこの私が、こんな屈辱を……", "page65537_fc1", 2],
      :orgasm_word => ["【コーネリア】\nこの体、快楽に反応させられるなんて……", "page65537_fc1", 2],
      :predation_word => ["【コーネリア】\n私が、食べられるなんて……！\nお、覚えておくのですね……きゃぁぁ！", "page65537_fc1", 2],
      :incontinence_word => ["【コーネリア】\nみ、見ないで……！\nこんな、屈辱……！", "page65537_fc1", 2],
    },
    122 => { # ソフィア
      :dead_word => ["【ソフィア】\nああ、こんな……申し訳ありません……", "sisterlamia_fc1", 2],
      :orgasm_word => ["【ソフィア】\n神よ、このような快感を……\nあぁぁぁ……！", "sisterlamia_fc1", 2],
      :predation_word => ["【ソフィア】\nこんな、私が糧となるなんて……\nきゃぁぁ！", "sisterlamia_fc1", 2],
      :incontinence_word => ["【ソフィア】\nああ、こんな恥ずかしい事を……\n神よ、私をお許し下さい……", "sisterlamia_fc1", 2],
    },
    123 => { # シス
      :dead_word => ["【クリスティー】\nああ、なんという事でしょう……", "sisccubus_fc1", 2],
      :orgasm_word => ["【クリスティー】\n体が悦んでしまう……\n神よ、罪深き私をお許しを……", "sisccubus_fc1", 2],
      :predation_word => ["【クリスティー】\nやめて下さい、こんな……\nあぁぁぁぁ……！", "sisccubus_fc1", 2],
      :incontinence_word => ["【クリスティー】\nああ……こんな姿、見られてしまうなんて……", "sisccubus_fc1", 2],
    },
    124 => { # 杏奈
      :dead_word => ["【杏奈】\nもう戦えない……ばたっ。", "arikui_fc1", 2],
      :orgasm_word => ["【杏奈】\nダメ、感じすぎ……あぁぁぁ！", "arikui_fc1", 2],
      :predation_word => ["【杏奈】\nた、食べないでぇ……！\nいやぁぁぁぁ！", "arikui_fc1", 2],
      :incontinence_word => ["【杏奈】\nちょっとぉ、見ないでよぉ……\nだめぇぇぇぇ……", "arikui_fc1", 2],
    },
    125 => { # アイシャ
      :dead_word => ["【アイシャ】\nうがが……もう戦えないぞ……", "grizzly_fc1", 2],
      :orgasm_word => ["【アイシャ】\nはぅぅ……こんな感覚、初めてだぞ……", "grizzly_fc1", 2],
      :predation_word => ["【アイシャ】\nあたしを食べるなんて……！", "grizzly_fc1", 2],
      :incontinence_word => ["【アイシャ】\n恥ずかしいから……見ないでほしいぞ……", "grizzly_fc1", 2],
    },
    126 => { # ロビン
      :dead_word => ["【ロビン】\n体が……動かない……", "XX-7_fc1", 0],
      :orgasm_word => ["【ロビン】\n私が……感じさせられるなんて……", "XX-7_fc1", 0],
      :predation_word => ["【ロビン】\n私が……食べられるなんて……", "XX-7_fc1", 0],
      :incontinence_word => ["【ロビン】\n私が……漏らすなんて……", "XX-7_fc1", 0],
    },
    127 => { # リッピー
      :dead_word => ["【リッピー】\nアタシ、もうだめなのか……", "littlebug_fc1", 2],
      :orgasm_word => ["【リッピー】\nこんな、気持ちいいぞ……", "littlebug_fc1", 3],
      :predation_word => ["【リッピー】\nアタシを食べるのか！？\nやだ、やだぁ……", "littlebug_fc1", 2],
      :incontinence_word => ["【リッピー】\nアタシが漏らすなんて……\nはふぅぅ……", "littlebug_fc1", 3],
    },
    128 => { # ジリアン
      :dead_word => ["【ジリアン】\nくっ、体が動かない……", "kaniloid_fc1", 2],
      :orgasm_word => ["【ジリアン】\nこんな快感……\nあぁぁぁ……", "kaniloid_fc1", 2],
      :predation_word => ["【ジリアン】\n私が食べられるなんて……こんな……\nあぁぁぁぁぁ！", "kaniloid_fc1", 2],
      :incontinence_word => ["【ジリアン】\n体液が……漏れ出てしまう……", "kaniloid_fc1", 2],
    },
    129 => { # ヒルデ
      :dead_word => ["【ヒルデ】\n私の体……動かない……", "brunhild_fc1", 2],
      :orgasm_word => ["【ヒルデ】\nこれ、だめ……体が変になる……！", "brunhild_fc1", 4],
      :predation_word => ["【ヒルデ】\n私、食べられるの？\nこんなの、イヤ……", "brunhild_fc1", 2],
      :incontinence_word => ["【ヒルデ】\nなにか漏れちゃう……\n不思議、でも気持ちいい……", "brunhild_fc1", 4],
    },
    130 => { # キャリー
      :dead_word => ["【キャリー】\nまた、死んでしまうの……？", "ghost_fc1", 0],
      :orgasm_word => ["【キャリー】\n気持ちいい……でも、いやだ……", "ghost_fc1", 0],
      :predation_word => ["【キャリー】\n幽霊を……食べるなんて……", "ghost_fc1", 0],
      :incontinence_word => ["【キャリー】\n幽霊でも……漏らすのね……", "ghost_fc1", 0],
    },
    131 => { # みやび
      :dead_word => ["【みやび】\nあそびたい……もっと……", "doll_fc1", 2],
      :orgasm_word => ["【みやび】\n変なかんじ……からだが、おかしくなる……", "doll_fc1", 2],
      :predation_word => ["【みやび】\nたべないで……いやだ……", "doll_fc1", 2],
      :incontinence_word => ["【みやび】\nもらしちゃう……ごめんなさい……", "doll_fc1", 2],
    },
    132 => { # エリィ
      :dead_word => ["【エリィ】\nぁぁぁ……", "zonbe_fc2", 0],
      :orgasm_word => ["【エリィ】\nはぅぅ、あぁぁ……", "zonbe_fc2", 0],
      :predation_word => ["【エリィ】\nあぐ、うぅぅ……", "zonbe_fc2", 0],
      :incontinence_word => ["【エリィ】\nあ、あぁぁ……", "zonbe_fc2", 0],
    },
    133 => { # ゾンビーズ
      :dead_word => ["【ゾンビーズ】\nう……ぁぁ……", "zonbe_fc3", 3],
      :orgasm_word => ["【ゾンビーズ】\nはぅ、うぅぅ……", "zonbe_fc3", 3],
      :predation_word => ["【ゾンビーズ】\nあ……あぁぁ……", "zonbe_fc3", 3],
      :incontinence_word => ["【ゾンビーズ】\nうぁ……あ、あぁぁ……", "zonbe_fc3", 3],
    },
    134 => { # クロム
      :dead_word => ["【クロム】\nもうダメなのじゃ……", "chrom_fc1", 6],
      :orgasm_word => ["【クロム】\nだ、だめ……イっちゃうのじゃ……\nはぅぅぅぅ……", "chrom_fc1", 5],
      :predation_word => ["【クロム】\nた、食べないでぇ……\nひゃぁぁぁぁ！", "chrom_fc1", 6],
      :incontinence_word => ["【クロム】\nお、オモラシしちゃうのじゃ……\n恥ずかしい……あぁぁ……", "chrom_fc1", 6],
    },
    135 => { # フレデリカ
      :dead_word => ["【フレデリカ】\n体が、動かない……", "frederika_fc1", 2],
      :orgasm_word => ["【フレデリカ】\nこの感じ……体がおかしい……", "frederika_fc1", 1],
      :predation_word => ["【フレデリカ】\n私が……食べられるの……", "frederika_fc1", 2],
      :incontinence_word => ["【フレデリカ】\n漏らしてしまう……", "frederika_fc1", 1],
    },
    136 => { # クローディア
      :dead_word => ["【クローディア】\nこれ以上、戦えないわ……", "elf_fc1", 2],
      :orgasm_word => ["【クローディア】\nああ、イっちゃう……\nイくところ、みんなに見られてるぅ……", "elf_fc1", 2],
      :predation_word => ["【クローディア】\nちょっと、食べるのはやめて……\n犯すのはいいから、食べるのは……あ、あぁぁ！", "elf_fc1", 2],
      :incontinence_word => ["【クローディア】\nやめてぇ……漏らしちゃうとこ、見ないでぇ……\nあぁぁぁぁ……", "elf_fc1", 2],
    },
    137 => { # ラブ＆ラム
      :dead_word => ["【ラブ＆ラム】\nおやすみ……", "braunys_fc2", 0],
      :orgasm_word => ["【ラブ＆ラム】\nイっちゃうよぉ……", "braunys_fc2", 0],
      :predation_word => ["【ラブ＆ラム】\nやだぁ！　食べないでよぉ……！", "braunys_fc2", 0],
      :incontinence_word => ["【ラブ＆ラム】\nオモラシ、しちゃう……", "braunys_fc2", 0],
    },
    138 => { # ミル＆リル
      :dead_word => ["【ミル＆リル】\nうわ～", "tfairy_fc1", 2],
      :orgasm_word => ["【ミル＆リル】\nだめ、イっちゃうよぉ……", "tfairy_fc1", 2],
      :predation_word => ["【ミル＆リル】\n食べられるの、やだ～！", "tfairy_fc1", 2],
      :incontinence_word => ["【ミル＆リル】\n漏らしちゃうよぉ……", "tfairy_fc1", 2],
    },
    139 => { # フェアリーズ
      :dead_word => ["【フェアリーズ】\nうわ～", "fairys_fc1", 3],
      :orgasm_word => ["【フェアリーズ】\nわ～ん、気持ちいいよぉ～", "fairys_fc1", 3],
      :predation_word => ["【フェアリーズ】\n食べられちゃうよ～", "fairys_fc1", 3],
      :incontinence_word => ["【フェアリーズ】\n漏らしちゃうよ～", "fairys_fc1", 3],
    },
    140 => { # ラチュラ
      :dead_word => ["【ラチュラ】\nそんな、私がこんな所で……！", "taran_fc1", 2],
      :orgasm_word => ["【ラチュラ】\n私、イかされちゃうの……？", "taran_fc1", 2],
      :predation_word => ["【ラチュラ】\n嫌だ、私が食べられるなんて……", "taran_fc1", 2],
      :incontinence_word => ["【ラチュラ】\nああ、漏らしちゃう……", "taran_fc1", 2],
    },
    141 => { # ミナ
      :dead_word => ["【ミナ】\nくっ、やりやがる……！", "mino_fc1", 2],
      :orgasm_word => ["【ミナ】\nやめろぉ……\nあたしがイくとこ、見るなよぉ……", "mino_fc1", 2],
      :predation_word => ["【ミナ】\nた、食べるな……このぉ！\nいやだぁ、あぁぁぁぁ……！", "mino_fc1", 2],
      :incontinence_word => ["【ミナ】\nやめろぉ……\nあたしが漏らすとこ、見るなよぉ……", "mino_fc1", 2],
    },
    142 => { # バナッチ
      :dead_word => ["【バナッチ】\nくっ、無念……", "bander_fc1", 2],
      :orgasm_word => ["【バナッチ】\nこんな、私が……あぁぁ……", "bander_fc1", 2],
      :predation_word => ["【バナッチ】\nやめろ……ぐっ……！\nあぁぁぁ……", "bander_fc1", 2],
      :incontinence_word => ["【バナッチ】\n私が漏らすだと？\nそんな……ぐぅぅ……", "bander_fc1", 2],
    },
    143 => { # エヴァ
      :dead_word => ["【エヴァ】\nなんで、私が……！\n私ばっかり、こんな……！", "eva_fc1", 2],
      :orgasm_word => ["【エヴァ】\nサキュバスなのにぃ……\nイかされるなんて、恥ずかしいよぉ……", "eva_fc1", 2],
      :predation_word => ["【エヴァ】\nやめて、食べるなら別のヒトを……\nいやぁぁぁぁ……！", "eva_fc1", 2],
      :incontinence_word => ["【エヴァ】\n見ないで！　見ないでよぉ……\nうぅぅっ……", "eva_fc1", 2],
    },
    144 => { # サニー
      :dead_word => ["【サニー】\nちょっと、ひどいじゃない……", "saboresu_fc1", 2],
      :orgasm_word => ["【サニー】\nこんなの、感じすぎちゃうよ……", "saboresu_fc1", 2],
      :predation_word => ["【サニー】\nた、食べないで……きゃぁっ！", "saboresu_fc1", 2],
      :incontinence_word => ["【サニー】\nごめん、漏らしちゃった……", "saboresu_fc1", 2],
    },
    145 => { # ヴァネッサ
      :dead_word => ["【ヴァネッサ】\n私の甲殻が役に立たないなんて……", "mukade_fc1", 2],
      :orgasm_word => ["【ヴァネッサ】\nどれだけ固くても、快楽は防げないわ……", "mukade_fc1", 2],
      :predation_word => ["【ヴァネッサ】\n私の不味さは有名よ……\nだから、やめて……あぁぁぁ！", "mukade_fc1", 2],
      :incontinence_word => ["【ヴァネッサ】\nああ、漏らしちゃう……", "mukade_fc1", 2],
    },
    146 => { # スカーレット
      :dead_word => ["【スカーレット】\nまさか、私が……！", "sasori_fc1", 2],
      :orgasm_word => ["【スカーレット】\n砂漠で、こんな気持ちいいコトなかったわ……", "sasori_fc1", 2],
      :predation_word => ["【スカーレット】\n私なんて、肉があんまりないのに……\nきゃぁぁ！", "sasori_fc1", 2],
      :incontinence_word => ["【スカーレット】\nくっ、なんて屈辱……", "sasori_fc1", 2],
    },
    147 => { # キャスタ
      :dead_word => ["【キャスタ】\nああ、少し休ませてもらいますわ……", "saboten_fc1", 2],
      :orgasm_word => ["【キャスタ】\nこんなに気持ちいいこと、今まで……\nあ、あぁぁぁ……", "saboten_fc1", 2],
      :predation_word => ["【キャスタ】\n私を食べると痛いですわ……\nだから……きゃぁぁ！", "saboten_fc1", 2],
      :incontinence_word => ["【キャスタ】\nやめて、こちらを見ないで……\nあぁぁぁぁ……", "saboten_fc1", 2],
    },
    148 => { # ミュー
      :dead_word => ["【ミュー】\nもうあたし、走れません……", "datyou_fc1", 2],
      :orgasm_word => ["【ミュー】\n気持ちいいの、もうやだぁ……", "datyou_fc1", 2],
      :predation_word => ["【ミュー】\n食べないで下さい……\nあ、やぁぁぁぁ！", "datyou_fc1", 2],
      :incontinence_word => ["【ミュー】\n漏らすところ、見られちゃうなんて……", "datyou_fc1", 2],
    },
    149 => { # ジーニー
      :dead_word => ["【ジーニー】\n少しランプの中に戻るとしましょう……", "lamp_fc1", 2],
      :orgasm_word => ["【ジーニー】\nこんな、私が絶頂するなんて……", "lamp_fc1", 2],
      :predation_word => ["【ジーニー】\nこの私を喰らうなど……\nそんな……きゃぁっ！", "lamp_fc1", 2],
      :incontinence_word => ["【ジーニー】\n私が漏らすところなど……\n見ないで……はぅぅぅ……", "lamp_fc1", 2],
    },
    150 => { # パトラ
      :dead_word => ["【パトラ】\n我は……少し眠るぞ……", "mummy_fc1", 2],
      :orgasm_word => ["【パトラ】\nこんな……我が女の本能が……", "mummy_fc1", 2],
      :predation_word => ["【パトラ】\n我を喰らうなど……\n美味くもないぞ……", "mummy_fc1", 2],
      :incontinence_word => ["【パトラ】\n我にこんな水分が残っていたか……", "mummy_fc1", 2],
    },
    151 => { # ライラ
      :dead_word => ["【ライラ】\nこの私が、不覚を取るなんて……！", "kobura_fc1", 2],
      :orgasm_word => ["【ライラ】\n私がイカされるなんて……はぅぅ……", "kobura_fc1", 2],
      :predation_word => ["【ライラ】\n私が食べられるなんて、許さないわ……\nきゃぁぁ！", "kobura_fc1", 2],
      :incontinence_word => ["【ライラ】\nこんなところで尿を垂れ流すなんて……", "kobura_fc1", 2],
    },
    152 => { # ネフェルラミアス
      :dead_word => ["【ネフェルラミアス】\nきゃぁっ……！", "lamias_fc2", 4],
      :orgasm_word => ["【ネフェルラミアス】\nだめ、イっちゃう……！", "lamias_fc2", 4],
      :predation_word => ["【ネフェルラミアス】\n食べないで……\n私はいいから、妹たちは……", "lamias_fc2", 4],
      :incontinence_word => ["【ネフェルラミアス】\nだめ、漏れちゃう……", "lamias_fc2", 4],
    },
    153 => { # スフィンクス
      :dead_word => ["【スフィンクス】\nこの妾が……なんという屈辱……", "sphinx_fc1", 2],
      :orgasm_word => ["【スフィンクス】\nこのような快感、何百年ぶりか……", "sphinx_fc1", 2],
      :predation_word => ["【スフィンクス】\n妾が、食べられるとは……", "sphinx_fc1", 2],
      :incontinence_word => ["【スフィンクス】\n妾が、このような惨めな姿をさらすとは……", "sphinx_fc1", 2],
    },
    154 => { # ガー
      :dead_word => ["【ガー】\nあたし……もうダメ……", "wani_fc1", 2],
      :orgasm_word => ["【ガー】\nあたし……もうイっちゃう……", "wani_fc1", 2],
      :predation_word => ["【ガー】\nあたしが食べられるの……？", "wani_fc1", 2],
      :incontinence_word => ["【ガー】\nあたし、漏らしちゃう……", "wani_fc1", 2],
    },
    155 => { # サキ
      :dead_word => ["【サキ】\nファンのみんな、先に逝ってるね……", "saki_fc1", 2],
      :orgasm_word => ["【サキ】\nこんな姿、ファンには見せられないよぉ……", "saki_fc1", 2],
      :predation_word => ["【サキ】\nあたし、食べられちゃうの？\nやだ、やだよぉ……", "saki_fc1", 2],
      :incontinence_word => ["【サキ】\nだめ、漏れちゃう……\nファンは喜んでくれる？　幻滅される……？", "saki_fc1", 2],
    },
    156 => { # レジーナ
      :dead_word => ["【レジーナ】\nこれも、戦士の掟よね……", "d_fighter_fc1", 0],
      :orgasm_word => ["【レジーナ】\nイっちゃう……恥ずかしいよぉ……", "d_fighter_fc1", 2],
      :predation_word => ["【レジーナ】\n食べないでぇ……やだよぉ……\nきゃぁぁぁ！", "d_fighter_fc1", 0],
      :incontinence_word => ["【レジーナ】\n漏らしちゃう……見ないでぇ……", "d_fighter_fc1", 2],
    },
    157 => { # アシダカ
      :dead_word => ["【アシダカ】\nうぐぐ……もう体が動かないよぉ……", "oogumo_fc1", 2],
      :orgasm_word => ["【アシダカ】\nこんな、あたしがイかされるなんてぇ……", "oogumo_fc1", 2],
      :predation_word => ["【アシダカ】\nた、食べないでよぉ……きゃぁぁ！", "oogumo_fc1", 2],
      :incontinence_word => ["【アシダカ】\n漏らしちゃうよぉ……はぅぅ。", "oogumo_fc1", 2],
    },
    158 => { # アンナ
      :dead_word => ["【アンナ】\n……………………", "suckvore_fc1", 2],
      :orgasm_word => ["【アンナ】\n……………………", "suckvore_fc1", 2],
      :predation_word => ["【アンナ】\n……………………", "suckvore_fc1", 2],
      :incontinence_word => ["【アンナ】\n……………………", "suckvore_fc1", 2],
    },
    159 => { # メイデン
      :dead_word => ["【メイデン】\n……………………", "ironmaiden_fc1", 0],
      :orgasm_word => ["【メイデン】\n……………………", "ironmaiden_fc1", 0],
      :predation_word => ["【メイデン】\n……………………", "ironmaiden_fc1", 0],
      :incontinence_word => ["【メイデン】\n……………………", "ironmaiden_fc1", 0],
    },
    160 => { # ユリア
      :dead_word => ["【ユリア】\nもうだめ……もっと力を……", "wormv_fc1", 2],
      :orgasm_word => ["【ユリア】\nきもちいい……もっと……", "wormv_fc1", 2],
      :predation_word => ["【ユリア】\n食べられるの……\nそんなの、嫌よ……あぁぁ……", "wormv_fc1", 2],
      :incontinence_word => ["【ユリア】\n漏らすのも、気持ちいいけど……", "wormv_fc1", 2],
    },
    161 => { # レモン
      :dead_word => ["【レモン】\n少し休むわね、ふぅ……", "ustrel_fc1", 2],
      :orgasm_word => ["【レモン】\nイかされちゃうの……？\nだめ、そんな……あぅぅ……", "ustrel_fc1", 2],
      :predation_word => ["【レモン】\nた、食べるのだけはやめて……！\nきゃぁぁぁ！", "ustrel_fc1", 2],
      :incontinence_word => ["【レモン】\nこんなところでオシッコしちゃうなんて……", "ustrel_fc1", 2],
    },
    162 => { # 蜜壺
      :dead_word => ["【蜜壺】\n壺に引きこもっていたらよかったわ……", "mitutubo_fc1", 2],
      :orgasm_word => ["【蜜壺】\nああ、こんな……壺の中、もうドロドロ……", "mitutubo_fc1", 2],
      :predation_word => ["【蜜壺】\nちょっと、壺ごと食べるなんて……！", "mitutubo_fc1", 2],
      :incontinence_word => ["【蜜壺】\n壺の中に、漏らしていい……？", "mitutubo_fc1", 2],
    },
    163 => { # リリィ
      :dead_word => ["【リリィ】\nこんなところで、また地を這うの……？", "lily_fc1", 6],
      :orgasm_word => ["【リリィ】\nこの私が、こんな屈辱……！\nあぁぁぁぁ……！", "lily_fc1", 6],
      :predation_word => ["【リリィ】\nふん、好きにすればいいわ……", "lily_fc1", 5],
      :incontinence_word => ["【リリィ】\nこんな屈辱、絶対に許さないわ……！\n絶対に……絶対に……！", "lily_fc1", 6],
    },
    164 => { # 雫
      :dead_word => ["【雫】\nもう無理、ちょっと休ませてよ……", "kooni_fc1", 2],
      :orgasm_word => ["【雫】\nこんなのヒキョーだよ、あぅぅぅん……", "kooni_fc1", 2],
      :predation_word => ["【雫】\nちょっと、嘘でしょ……？\n食べられるの嫌ぁぁぁ！", "kooni_fc1", 2],
      :incontinence_word => ["【雫】\nこんなの……恥ずかしいよぉ……", "kooni_fc1", 2],
    },
    165 => { # ナホ
      :dead_word => ["【ナホ】\nもう戦えませんよぉ……", "onaho_fc1", 2],
      :orgasm_word => ["【ナホ】\nあたしがイかされるなんて、おかしいです……", "onaho_fc1", 2],
      :predation_word => ["【ナホ】\nぷにょぷにょやわらかだけど、おいしくないですよぉ……", "onaho_fc1", 2],
      :incontinence_word => ["【ナホ】\nああ、漏らしちゃいますよぉ……", "onaho_fc1", 2],
    },
    166 => { # ナビス
      :dead_word => ["【ナビス】\nまだまだ、お仕事しなくちゃいけないのに……", "narcubus_fc1", 2],
      :orgasm_word => ["【ナビス】\nはぅぅ、こんなぁ……\nあたし、イっちゃいます……", "narcubus_fc1", 2],
      :predation_word => ["【ナビス】\n食べられるのは嫌ですよぉ……", "narcubus_fc1", 2],
      :incontinence_word => ["【ナビス】\nあたし、いけない看護婦さんです……\nオモラシしちゃうなんて……", "narcubus_fc1", 2],
    },
    167 => { # ルシア
      :dead_word => ["【ルシア】\n私の力が、通じないなんて……", "lusia_fc1", 2],
      :orgasm_word => ["【ルシア】\nこんな屈辱……！\n覚えておきなさい……！", "lusia_fc1", 2],
      :predation_word => ["【ルシア】\n私を食べるなんて……そんな……", "lusia_fc1", 2],
      :incontinence_word => ["【ルシア】\nこ、こんな姿をさらすなんて……", "lusia_fc1", 2],
    },
    168 => { # まなこ
      :dead_word => ["【まなこ】\nちょっと休ませてよね……", "dodome_fc1", 2],
      :orgasm_word => ["【まなこ】\n私がイかされるの……\nあ、あぁぁぁ……！", "dodome_fc1", 2],
      :predation_word => ["【まなこ】\n食べないで、食べないでよぉ……", "dodome_fc1", 2],
      :incontinence_word => ["【まなこ】\n漏らしちゃうなんて、やだぁ……", "dodome_fc1", 2],
    },
    169 => { # リル
      :dead_word => ["【リル】\nあたしが負けるなんて……！", "lizardthief_fc1", 2],
      :orgasm_word => ["【リル】\nくそっ、こんな奴にイかされるなんてぇ……\nはぅぅぅぅ……", "lizardthief_fc1", 2],
      :predation_word => ["【リル】\nやめろ、食うなぁ……！\nぎゃぁぁ！", "lizardthief_fc1", 2],
      :incontinence_word => ["【リル】\nくそっ、あたしが漏らしちまうなんて……", "lizardthief_fc1", 2],
    },
    170 => { # レン
      :dead_word => ["【レン】\n私の方が弱かったようですね……", "lizardthief_fc2", 2],
      :orgasm_word => ["【レン】\nイかされるなんて、こんな屈辱……\nあぁぁぁぁ……", "lizardthief_fc2", 2],
      :predation_word => ["【レン】\nどうか、食べるのはやめて……\nきゃぁぁぁ！", "lizardthief_fc2", 2],
      :incontinence_word => ["【レン】\nこんなところで漏らすなんて……", "lizardthief_fc2", 2],
    },
    171 => { # ミランダ
      :dead_word => ["【ミランダ】\nくっ、不覚を取っちまったか……！", "lizardboss_fc1", 2],
      :orgasm_word => ["【ミランダ】\n畜生、このあたしが……\nあぁぁぁぁぁ……！", "lizardboss_fc1", 5],
      :predation_word => ["【ミランダ】\nあたしを食べるだなんて、そんな事……！\nあぁぁぁぁぁ！", "lizardboss_fc1", 2],
      :incontinence_word => ["【ミランダ】\nくそっ、見るんじゃないよ……\nあっ、ダメ……漏れる……", "lizardboss_fc1", 5],
    },
    172 => { # ミラージュ
      :dead_word => ["【ミラージュ】\nばたんきゅう……", "sinkiro_fc1", 3],
      :orgasm_word => ["【ミラージュ】\n蜃気楼なのに、イっちゃうなんて……", "sinkiro_fc1", 2],
      :predation_word => ["【ミラージュ】\n蜃気楼を食べたって美味しくないです……\nひゃぁぁぁ！", "sinkiro_fc1", 3],
      :incontinence_word => ["【ミラージュ】\nも、漏れちゃいます……\nやだぁ、こんなの……", "sinkiro_fc1", 2],
    },
    173 => { # ヘレン
      :dead_word => ["【ヘレン】\nくっ……獲物のくせに……！", "arizigoku_fc1", 2],
      :orgasm_word => ["【ヘレン】\nやだ、イかされるなんて……", "arizigoku_fc1", 2],
      :predation_word => ["【ヘレン】\nあたしを食べるなんて、いい根性ね……！", "arizigoku_fc1", 2],
      :incontinence_word => ["【ヘレン】\nあたしが漏らすなんて……", "arizigoku_fc1", 2],
    },
    174 => { # ダリア
      :dead_word => ["【ダリア】\nいたい……", "sandw_fc1", 2],
      :orgasm_word => ["【ダリア】\nきもちいい……", "sandw_fc1", 2],
      :predation_word => ["【ダリア】\nたべられるなんて……", "sandw_fc1", 2],
      :incontinence_word => ["【ダリア】\nもらしちゃう……\nおぼれないようにしてね……", "sandw_fc1", 2],
    },
    175 => { # ディジィ
      :dead_word => ["【ディジィ】\nこんなの、やだー！", "d_scylla_fc1", 2],
      :orgasm_word => ["【ディジィ】\nやだぁ、イっちゃうよぉ……！", "d_scylla_fc1", 2],
      :predation_word => ["【ディジィ】\n食べられるの、やだぁ……！", "d_scylla_fc1", 2],
      :incontinence_word => ["【ディジィ】\nオモラシするの、やだぁ……", "d_scylla_fc1", 2],
    },
    176 => { # ヴィタエ
      :dead_word => ["【ヴィタエ】\nここで果てますか、無念です……", "vitae_fc1", 2],
      :orgasm_word => ["【ヴィタエ】\nこの私が、絶頂してしまうなんて……", "vitae_fc1", 2],
      :predation_word => ["【ヴィタエ】\nこの私が、捕食されてしまうなんて……", "vitae_fc1", 2],
      :incontinence_word => ["【ヴィタエ】\nああ、体液が漏れ出して……", "vitae_fc1", 2],
    },
    177 => { # ヴェータラ
      :dead_word => ["【ヴェータラ】\n腹が立つわねぇ、こんな扱い……", "vetala_fc1", 2],
      :orgasm_word => ["【ヴェータラ】\nああ、感じちゃうわぁ……", "vetala_fc1", 2],
      :predation_word => ["【ヴェータラ】\nこの私が、食べられる側なんて……", "vetala_fc1", 2],
      :incontinence_word => ["【ヴェータラ】\n屈辱、惨め……こんな……", "vetala_fc1", 2],
    },
    178 => { # ヴァルト
      :dead_word => ["【ヴァルト】\n各部、機関停止……", "valt_fc1", 2],
      :orgasm_word => ["【ヴァルト】\n快楽、耐久不可能……", "valt_fc1", 2],
      :predation_word => ["【ヴァルト】\n捕食される……", "valt_fc1", 2],
      :incontinence_word => ["【ヴァルト】\n尿液、排出……", "valt_fc1", 2],
    },
    179 => { # シニファ
      :dead_word => ["【シニファ】\nあははは……", "sinifa_fc1", 2],
      :orgasm_word => ["【シニファ】\nフフ、ハハハー！", "sinifa_fc1", 3],
      :predation_word => ["【シニファ】\nひぁ、はははははは……！", "sinifa_fc1", 2],
      :incontinence_word => ["【シニファ】\nはふ、はははぁ……", "sinifa_fc1", 3],
    },
    180 => { # シャドー
      :dead_word => ["【シャドー】\n影の世界に……戻る……", "shadow_fc1", 0],
      :orgasm_word => ["【シャドー】\n絶頂……する……", "shadow_fc1", 0],
      :predation_word => ["【シャドー】\n影が……捕食されるなんて……", "shadow_fc1", 0],
      :incontinence_word => ["【シャドー】\n尿が……漏れ出る……", "shadow_fc1", 0],
    },
    181 => { # リザ
      :dead_word => ["【リザ】\n私の力が……失われていく……", "gaistvine_fc1", 1],
      :orgasm_word => ["【リザ】\nああ、気持ちいい……", "gaistvine_fc1", 1],
      :predation_word => ["【リザ】\n食べられるのは嫌……", "gaistvine_fc1", 1],
      :incontinence_word => ["【リザ】\n漏らすなんて、嫌……", "gaistvine_fc1", 1],
    },
    182 => { # クロウリー
      :dead_word => ["【クロウリー】\n私の……力……", "c_homunculus_fc1", 2],
      :orgasm_word => ["【クロウリー】\nこの快楽……耐えきれない……", "c_homunculus_fc1", 2],
      :predation_word => ["【クロウリー】\n私が……捕食されるなんて……", "c_homunculus_fc1", 2],
      :incontinence_word => ["【クロウリー】\n私が……尿を垂れ流すなんて……", "c_homunculus_fc1", 2],
    },
    183 => { # トーチャ
      :dead_word => ["【トーチャ】\n罪人を……処分……", "ironmaiden_k_fc1", 2],
      :orgasm_word => ["【トーチャ】\nこの快楽……私も、罪人……", "ironmaiden_k_fc1", 2],
      :predation_word => ["【トーチャ】\n私が……捕食されるなど……", "ironmaiden_k_fc1", 2],
      :incontinence_word => ["【トーチャ】\n私が……失禁するなど……", "ironmaiden_k_fc1", 2],
    },
    184 => { # フランチェスカ
      :dead_word => ["【フランチェスカ】\nこんな……ジャンクになっちゃう……", "junkdoll_fc2", 1],
      :orgasm_word => ["【フランチェスカ】\nああ……感じちゃうよぉ……", "junkdoll_fc2", 1],
      :predation_word => ["【フランチェスカ】\n人形を食べるなんて……\nへ、変態……！", "junkdoll_fc2", 1],
      :incontinence_word => ["【フランチェスカ】\nなんでこんな機能あるのよぉ……", "junkdoll_fc2", 1],
    },
    185 => { # ラディオ
      :dead_word => ["【ラディオ】\n機能停止シマす……", "radio_fc1", 0],
      :orgasm_word => ["【ラディオ】\nこんな機能ガ、私にも……", "radio_fc1", 0],
      :predation_word => ["【ラディオ】\n私は美味しクアリません……\nボディに味付けは施されてオリマせん……", "radio_fc1", 0],
      :incontinence_word => ["【ラディオ】\n体液が漏れテイマす……\nこれは、イッタい……", "radio_fc1", 0],
    },
    525 => { # ソニア
      :dead_word => ["【ソニア】\nごめんね、ルカ……", "sonia_fc2", 2],
      :orgasm_word => ["【ソニア】\nだめ、だめぇ……\nこんなの、イっちゃうよぉぉ……", "sonia_fc2", 0],
      :predation_word => ["【ソニア】\nやだ、やだ、やだよぉ……\nきゃぁぁぁ！", "sonia_fc3", 7],
      :incontinence_word => ["【ソニア】\nだめ、だめぇ……\nルカ、見ないでよぉ……", "sonia_fc2", 0],
    },
    529 => { # サラ
      :dead_word => ["【サラ】\nごめんなさい、お父様……", "sara_fc1", 4],
      :orgasm_word => ["【サラ】\nやだ、こんな辱め……\nあ、あぁぁぁぁ……！", "sara_fc1", 4],
      :predation_word => ["【サラ】\nた、食べないで……\nあぁぁぁぁ……！", "sara_fc1", 4],
      :incontinence_word => ["【サラ】\nやだよぉ、こんな人前で……\nはぅぅ……もうお嫁に行けない……", "sara_fc1", 4],
    },
    530 => { # サラ
      :dead_word => ["【サラ】\nああ……力が入らない……", "sara_fc4", 2],
      :orgasm_word => ["【サラ】\n気持ちいい……けど、屈辱……", "sara_fc4", 2],
      :predation_word => ["【サラ】\nあたし、食べられるの……？", "sara_fc4", 2],
      :incontinence_word => ["【サラ】\nああ、漏らしちゃう……\nオシッコ、いっぱい出ちゃう……", "sara_fc4", 2],
    },
    531 => { # サン・イリア王
      :dead_word => ["【サン・イリア王】\n機能停止……\nおお神よ、いま御許へ……", "saniria_fc2", 0],
      :predation_word => ["【サン・イリア王】\nやめた方が良い、私の体は胃もたれするぞ……", "saniria_fc2", 0],
    },
    533 => { # グランドノア女王
      :dead_word => ["【グランドノア女王】\nこんなところで、私の志が……", "grandnoa_fc1", 2],
      :orgasm_word => ["【グランドノア女王】\nくっ……私が、こんな屈辱……", "grandnoa_fc1", 2],
      :predation_word => ["【グランドノア女王】\n私はともかく、メダルは食べないで……", "grandnoa_fc1", 2],
      :incontinence_word => ["【グランドノア女王】\nこの私が、人前で下着を濡らすなんて……", "grandnoa_fc1", 2],
    },
    540 => { # アミラ
      :dead_word => ["【アミラ】\nウソみたいでしょ。\n死んでるのよ、私……", "amira_fc1", 1],
      :orgasm_word => ["【アミラ】\n見て！　淫らな私を見て！", "amira_fc1", 2],
      :predation_word => ["【アミラ】\nかわいいラミア♪　食われてゆ～く～よ♪\nかな～しそ～な……待って、まだ歌ってる最中！", "amira_fc1", 1],
      :incontinence_word => ["【アミラ】\nらめぇ！　オモラシする私を見て！　見ないで！", "amira_fc1", 2],
    },
    541 => { # ピーハー
      :dead_word => ["【ピーハー】\nグェーッ", "piha_fc1", 0],
      :orgasm_word => ["【ピーハー】\nギョーッ", "piha_fc1", 0],
      :predation_word => ["【ピーハー】\nあたしは……おいしいわよ～♪\n……ホギャァァァァァァ！！", "piha_fc1", 0],
      :incontinence_word => ["【ピーハー】\nブシャァァァー！", "piha_fc1", 0],
    },
    542 => { # ドーメイマ
      :dead_word => ["【ドーメイマ】\nみ、水……", "domeima_fc1", 0],
      :orgasm_word => ["【ドーメイマ】\nびくびく……", "domeima_fc1", 0],
      :predation_word => ["【ドーメイマ】\n水……", "domeima_fc1", 0],
      :incontinence_word => ["【ドーメイマ】\nじょろろろ……", "domeima_fc1", 0],
    },
    544 => { # マリー
      :dead_word => ["【マリー】\n少し休ませてもらうわ……", "mob_maid_fc1", 0],
      :orgasm_word => ["【マリー】\n私が、イかされるなんて……", "mob_maid_fc1", 0],
      :predation_word => ["【マリー】\n覚悟はしていたわ……", "mob_maid_fc1", 0],
      :incontinence_word => ["【マリー】\nこんな……人前でなんて……", "mob_maid_fc1", 0],
    },
    545 => { # エリィ
      :dead_word => ["【エリィ】\nすみません、もうダメです……", "mob_murabito1_fc1", 0],
      :orgasm_word => ["【エリィ】\nああ……気持ちいいです……", "mob_murabito1_fc1", 0],
      :predation_word => ["【エリィ】\nイ、イヤ……あぁぁっ！", "mob_murabito1_fc1", 0],
      :incontinence_word => ["【エリィ】\nああっ、見ないで下さい……！", "mob_murabito1_fc1", 0],
    },
    546 => { # ステラ
      :dead_word => ["【ステラ】\nどうせ、こういう運命だし……", "mob_hurou_fc1", 1],
      :orgasm_word => ["【ステラ】\nああ、イっちゃう……", "mob_hurou_fc1", 1],
      :predation_word => ["【ステラ】\nあなたは、これで満腹よね……", "mob_hurou_fc1", 1],
      :incontinence_word => ["【ステラ】\n漏らしたからって……何よ……", "mob_hurou_fc1", 1],
    },
    547 => { # ドン・ダリア
      :dead_word => ["【ドン・ダリア】\nくっ、覚えてやがれ……", "dondaria_fc1", 0],
      :orgasm_word => ["【ドン・ダリア】\nヤキが回ったもんだ……", "dondaria_fc1", 0],
      :predation_word => ["【ドン・ダリア】\nもう、好きなようにしやがれ……", "dondaria_fc1", 0],
      :incontinence_word => ["【ドン・ダリア】\nこんな姿、見られちまうなんて……", "dondaria_fc1", 0],
    },
    548 => { # バニィちゃん
      :dead_word => ["【バニィちゃん】\n休んじゃいま～す♪", "mob_bunny1_fc1", 0],
      :orgasm_word => ["【バニィちゃん】\nイっちゃうよ～♪", "mob_bunny1_fc1", 0],
      :predation_word => ["【バニィちゃん】\n食べられちゃう～♪", "mob_bunny1_fc1", 0],
      :incontinence_word => ["【バニィちゃん】\nオモラシしちゃった～♪", "mob_bunny1_fc1", 0],
    },
    549 => { # ルイズ
      :dead_word => ["【ルイズ】\nこれで終わりかよ……", "mob_touzoku_fc1", 0],
      :orgasm_word => ["【ルイズ】\nはぅぅ……惨めだぜ……", "mob_touzoku_fc1", 0],
      :predation_word => ["【ルイズ】\nやめろ……あ。あぁぁっ！", "mob_touzoku_fc1", 0],
      :incontinence_word => ["【ルイズ】\nくそぉ……見るなよぉ……", "mob_touzoku_fc1", 0],
    },
    550 => { # メイリン
      :dead_word => ["【メイリン】\nもう疲れたぁ……", "mob_kakutou_fc1", 0],
      :orgasm_word => ["【メイリン】\nこんなの、初めてぇ……", "mob_kakutou_fc1", 0],
      :predation_word => ["【メイリン】\nイ、イヤ……", "mob_kakutou_fc1", 0],
      :incontinence_word => ["【メイリン】\n人前でなんてぇ……", "mob_kakutou_fc1", 0],
    },
    551 => { # ケイト
      :dead_word => ["【ケイト】\n不甲斐ない身、お許しを……", "mob_maid1_fc1", 0],
      :orgasm_word => ["【ケイト】\n快楽を味わってしまうなんて……", "mob_maid1_fc1", 0],
      :predation_word => ["【ケイト】\nじっくりご賞味下さい……", "mob_maid1_fc1", 0],
      :incontinence_word => ["【ケイト】\nこれは、とんだ粗相を……", "mob_maid1_fc1", 0],
    },
    552 => { # エリッサ
      :dead_word => ["【エリッサ】\nもうダメ……", "mob_elf1_fc1", 0],
      :orgasm_word => ["【エリッサ】\nはぅぅ……", "mob_elf1_fc1", 0],
      :predation_word => ["【エリッサ】\nやだぁ……", "mob_elf1_fc1", 0],
      :incontinence_word => ["【エリッサ】\nおもらし、見ちゃダメ……", "mob_elf1_fc1", 0],
    },
    553 => { # フィーズ
      :dead_word => ["【フィーズ】\n論文提出、遅れちゃう……", "mob_gakusya1_fc1", 1],
      :orgasm_word => ["【フィーズ】\nこんなの初めて……ひゃうん！", "mob_gakusya1_fc1", 1],
      :predation_word => ["【フィーズ】\nやだ……やだぁ……！！", "mob_gakusya1_fc1", 1],
      :incontinence_word => ["【フィーズ】\nイ、イヤ……こんなの、最低……", "mob_gakusya1_fc1", 1],
    },
    554 => { # ナイチンゲール
      :dead_word => ["【ナイチンゲール】\n誰か看護してくれるぅ……", "mob_nasu1_fc1", 0],
      :orgasm_word => ["【ナイチンゲール】\nああ、ステキ……", "mob_nasu1_fc1", 0],
      :predation_word => ["【ナイチンゲール】\nこんなの、感じちゃう……", "mob_nasu1_fc1", 0],
      :incontinence_word => ["【ナイチンゲール】\nああ、オモラシ見られてるぅ……", "mob_nasu1_fc1", 0],
    },
    555 => { # テレサ
      :dead_word => ["【テレサ】\nきゅう……", "mob_murabito2_fc1", 0],
      :orgasm_word => ["【テレサ】\nイっちゃう……", "mob_murabito2_fc1", 1],
      :predation_word => ["【テレサ】\nやだよぉ……", "mob_murabito2_fc1", 0],
      :incontinence_word => ["【テレサ】\n……見ないで。", "mob_murabito2_fc1", 1],
    },
    556 => { # マリア
      :dead_word => ["【マリア】\n今、神の御許へ……", "mob_sister1_fc1", 0],
      :orgasm_word => ["【マリア】\nこんな……いけません……", "mob_sister1_fc1", 0],
      :predation_word => ["【マリア】\nどうか、それだけは……\nいやぁぁぁ！！", "mob_sister1_fc1", 0],
      :incontinence_word => ["【マリア】\nああ、神よ……許し給え……", "mob_sister1_fc1", 0],
    },
    557 => { # ジャスカ
      :dead_word => ["【ジャスカ】\nヒーローも時には一休み……", "justice_fc1", 0],
      :orgasm_word => ["【ジャスカ】\nヒーローが、こんなぁ……はぅぅ……", "justice_fc1", 0],
      :predation_word => ["【ジャスカ】\nや、やめろ……あぁぁ――！！", "justice_fc1", 0],
      :incontinence_word => ["【ジャスカ】\nはぅぅぅ……\nこんな姿、子供には見せられない……", "justice_fc1", 0],
    },
    558 => { # ナイア
      :dead_word => ["【ナイア】\nお役に立てず、すみません……", "mob_uranai1_fc1", 2],
      :orgasm_word => ["【ナイア】\nき、気持ちいい……だめぇ……", "mob_uranai1_fc1", 2],
      :predation_word => ["【ナイア】\nやだ、やだ……あぁぁぁ！", "mob_uranai1_fc1", 2],
      :incontinence_word => ["【ナイア】\nは、恥ずかしい……です……", "mob_uranai1_fc1", 2],
    },
    559 => { # サラーン
      :dead_word => ["【サラーン】\n無念……", "mob_assasin1_fc1", 0],
      :orgasm_word => ["【サラーン】\nこの私が、痴態をさらすなど……", "mob_assasin1_fc1", 0],
      :predation_word => ["【サラーン】\nこの私が、餌となるなど……", "mob_assasin1_fc1", 0],
      :incontinence_word => ["【サラーン】\nくっ……見るな……！", "mob_assasin1_fc1", 0],
    },
    560 => { # メロディ
      :dead_word => ["【メロディ】\n疲れたよ……", "mob_odoriko1_fc1", 0],
      :orgasm_word => ["【メロディ】\nキモチいいよぉ……", "mob_odoriko1_fc1", 0],
      :predation_word => ["【メロディ】\n食べちゃだめぇ……", "mob_odoriko1_fc1", 0],
      :incontinence_word => ["【メロディ】\nやめてぇ、見られちゃうよぉ……", "mob_odoriko1_fc1", 0],
    },
    561 => { # ウィッチ
      :dead_word => ["【ウィッチ】\n我ながら、情けないねぇ……", "mob_majyo1_fc1", 0],
      :orgasm_word => ["【ウィッチ】\nこんな、イかされるなんてぇ……", "mob_majyo1_fc1", 0],
      :predation_word => ["【ウィッチ】\nロクな味はしないよ……あぁぁぁ！", "mob_majyo1_fc1", 0],
      :incontinence_word => ["【ウィッチ】\nみ、見ないでおくれよ……", "mob_majyo1_fc1", 0],
    },
    562 => { # オーラン
      :dead_word => ["【オーラン】\nしばらく休むぜ……", "mob_bukiya1_fc1", 0],
      :orgasm_word => ["【オーラン】\nく、くそっ……屈辱だ……", "mob_bukiya1_fc1", 0],
      :predation_word => ["【オーラン】\n腹にもたれてやるから、覚悟しな……", "mob_bukiya1_fc1", 0],
      :incontinence_word => ["【オーラン】\n見るな……見るなよぉ……！", "mob_bukiya1_fc1", 0],
    },
    563 => { # ピラト
      :dead_word => ["【ピラト】\nしょせん、ここまでとは……", "People4", 7],
      :predation_word => ["【ピラト】\nうわぁぁぁぁ！！", "People4", 7],
    },
    564 => { # ヨハネ
      :dead_word => ["【ヨハネ】\n皆様、申し訳ありません……", "Actor1", 4],
      :predation_word => ["【ヨハネ】\nこんな……無念……", "Actor1", 4],
    },
    565 => { # サモン
      :dead_word => ["【サモン】\nここで……膝を折るか……", "Actor3", 6],
      :predation_word => ["【サモン】\n美味くもあるまいに……", "Actor3", 6],
    },
    566 => { # スカトロ大尉
      :dead_word => ["【スカトロ大尉】\n姉さん、助けてよ……姉さん……", "sukatoro_fc6", 0],
      :predation_word => ["【スカトロ大尉】\n（食べられる事を）強いられているんだ！", "sukatoro_fc15", 0],
    },
    567 => { # パンツ先生
      :dead_word => ["【パンツ先生】\n真っ白になって燃え尽きましたよ……", "pants_fc1", 3],
      :predation_word => ["【パンツ先生】\n皆さん、さようなら……", "pants_fc1", 3],
    },
  }
end

