# -*- encoding: utf-8 -*-
=begin
=図鑑_人物データ設定セクション by nwapeg

図鑑の人物の項に表示する内容を設定します。
解説のスクロールを実装した際に、制御文字の描画が不可能になりました。

==更新履歴
Date     Version Author Comment
14/11/30 0.3.0   トリス CG閲覧を追加
13/07/20 0.2.1   Foo    画像の拡縮率を可能に
13/07/20 0.2.0   Foo    画像にX,Y調整値指定可能に
                        解説から固有アビリティに変更
12/06/09 0.1.1   nwapeg 画像指定追加
12/06/08 0.1.0   nwapeg 試作

=end

#==============================================================================
# ■ NWConst::Library
#==============================================================================
module NWConst::Library
  # 回想・ＣＧ閲覧用背景（ピクチャフォルダ参照）
  ACTOR_DEFAULT_MEMORY_BG_IMAGE = "bg195"
  
  # 回想・ＣＧ閲覧用背景
  # :bb1 => 戦闘背景１から背景を選択します
  # :bb2 => 戦闘背景２から背景を選択します
  # :pic => ピクチャフォルダから背景を選択します
  ACTOR_MEMORY_BG_IMAGE = {
  }
  
  # ＣＧ閲覧用の画像設定
  # パス,ファイル名,色相,X調整値,Y調整値,拡縮率で記述します。
  # X座標の基準点は中央,Y座標の基準点は最下部です。
  # 色相以降の設定値は省略可能です。(デフォルト値:色相=0,X調整値=0,Y調整値=0,拡縮率=1.00)
  ACTOR_CG_VIEW_IMAGE = {
    5 => { # アリス
        :regist => {
          1 => ["Graphics/Pictures/", "ev_alice_H10_1"],
          2 => ["Graphics/Pictures/", "ev_alice_H10_2"],
          3 => ["Graphics/Pictures/", "ev_alice_H10_3"],
          4 => ["Graphics/Pictures/", "ev_alice_H10_4"],
          5 => ["Graphics/Pictures/", "ev_alice_H10_5"],
          6 => ["Graphics/Pictures/", "ev_alice_H10_6"],
          7 => ["Graphics/Pictures/", "ev_alice_H10_7"],
          8 => ["Graphics/Pictures/", "ev_alice_H10_8"],
          9 => ["Graphics/Pictures/", "ev_alice_H10_9"],
          10 => ["Graphics/Pictures/", "ev_alice_H14_1"],
          11 => ["Graphics/Pictures/", "ev_alice_H14_2"],
          12 => ["Graphics/Pictures/", "ev_alice_H14_3"],
          13 => ["Graphics/Pictures/", "ev_alice_H14_4"],
          14 => ["Graphics/Pictures/", "ev_alice_H14_5"],
          15 => ["Graphics/Pictures/", "ev_alice_H14_6"],
          16 => ["Graphics/Pictures/", "ev_alice_H14_7"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
        ],
      },
    12 => { # シルフ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_sylph_hb1"],
          2 => ["Graphics/Pictures/", "ev_sylph_hb2"],
          3 => ["Graphics/Pictures/", "ev_sylph_hb3"],
          4 => ["Graphics/Pictures/", "ev_sylph_hb4"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
        ],
      },
    13 => { # ノーム
        :regist => {
          1 => ["Graphics/Pictures/", "ev_gnome_hb1"],
          2 => ["Graphics/Pictures/", "ev_gnome_hb2"],
          3 => ["Graphics/Pictures/", "ev_gnome_hb3"],
          4 => ["Graphics/Pictures/", "ev_gnome_hb4"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
        ],
      },
    26 => { # イリアス
        :regist => {
          1 => ["Graphics/Pictures/", "ev_iriasu_hc1"],
          2 => ["Graphics/Pictures/", "ev_iriasu_hc2"],
          3 => ["Graphics/Pictures/", "ev_iriasu_hc3"],
          4 => ["Graphics/Pictures/", "ev_iriasu_hc4"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
        ],
      },
    41 => { # プロメスティン
        :regist => {
          1 => ["Graphics/Pictures/", "ev_stein_hsb1"],
          2 => ["Graphics/Pictures/", "ev_stein_hsb2"],
          3 => ["Graphics/Pictures/", "ev_stein_hsb3"],
          4 => ["Graphics/Pictures/", "ev_stein_hsb4"],
          5 => ["Graphics/Pictures/", "ev_stein_hsc1"],
          6 => ["Graphics/Pictures/", "ev_stein_hsc2"],
          7 => ["Graphics/Pictures/", "ev_stein_hsc3"],
          8 => ["Graphics/Pictures/", "ev_stein_hsc4"],
          9 => ["Graphics/Pictures/", "ev_stein_hsd1"],
          10 => ["Graphics/Pictures/", "ev_stein_hsd2"],
          11 => ["Graphics/Pictures/", "ev_stein_hsd3"],
          12 => ["Graphics/Pictures/", "ev_stein_hsd4"],
          13 => ["Graphics/Pictures/", "ev_stein_hse1"],
          14 => ["Graphics/Pictures/", "ev_stein_hse2"],
          15 => ["Graphics/Pictures/", "ev_stein_hse3"],
          16 => ["Graphics/Pictures/", "ev_stein_hse4"],
          17 => ["Graphics/Pictures/", "ev_stein_hsa1"],
          18 => ["Graphics/Pictures/", "ev_stein_hsa2"],
          19 => ["Graphics/Pictures/", "ev_stein_hsa3"],
          20 => ["Graphics/Pictures/", "ev_stein_hsa4"],
          21 => ["Graphics/Pictures/", "ev_stein_hsa5"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
        ],
      },
    53 => { # スライム娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_slime_hb1"],
          2 => ["Graphics/Pictures/", "ev_slime_hb2"],
          3 => ["Graphics/Pictures/", "ev_slime_hb3"],
          4 => ["Graphics/Pictures/", "ev_slime_hb4"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
        ],
      },
    55 => { # ナメクジ娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_name_hb01"],
          2 => ["Graphics/Pictures/", "ev_name_hb02"],
          3 => ["Graphics/Pictures/", "ev_name_hb03"],
          4 => ["Graphics/Pictures/", "ev_name_hb04"],
          5 => ["Graphics/Pictures/", "ev_name_hb05"],
          6 => ["Graphics/Pictures/", "ev_name_hb06"],
          7 => ["Graphics/Pictures/", "ev_name_hb07"],
          8 => ["Graphics/Pictures/", "ev_name_hb08"],
          9 => ["Graphics/Pictures/", "ev_name_hb09"],
          10 => ["Graphics/Pictures/", "ev_name_hb10"],
          11 => ["Graphics/Pictures/", "ev_name_hb11"],
          12 => ["Graphics/Pictures/", "ev_name_hb12"],
          13 => ["Graphics/Pictures/", "ev_name_hb13"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
        ],
      },
    56 => { # インプ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_inp_hd1"],
          2 => ["Graphics/Pictures/", "ev_inp_hd2"],
          3 => ["Graphics/Pictures/", "ev_inp_hd3"],
          4 => ["Graphics/Pictures/", "ev_inp_hd4"],
          5 => ["Graphics/Pictures/", "ev_inp_hd5"],
          6 => ["Graphics/Pictures/", "ev_inp_hd6"],
          7 => ["Graphics/Pictures/", "ev_inp_hd7"],
          8 => ["Graphics/Pictures/", "ev_inp_hd8"],
          9 => ["Graphics/Pictures/", "ev_inp_ha1"],
          10 => ["Graphics/Pictures/", "ev_inp_ha2"],
          11 => ["Graphics/Pictures/", "ev_inp_ha3"],
          12 => ["Graphics/Pictures/", "ev_inp_ha4"],
          13 => ["Graphics/Pictures/", "ev_inp_ha5"],
          14 => ["Graphics/Pictures/", "ev_inp_ha6"],
          15 => ["Graphics/Pictures/", "ev_inp_he1"],
          16 => ["Graphics/Pictures/", "ev_inp_he2"],
          17 => ["Graphics/Pictures/", "ev_inp_he3"],
          18 => ["Graphics/Pictures/", "ev_inp_he4"],
          19 => ["Graphics/Pictures/", "ev_inp_he5"],
          20 => ["Graphics/Pictures/", "ev_inp_hc1"],
          21 => ["Graphics/Pictures/", "ev_inp_hc2"],
          22 => ["Graphics/Pictures/", "ev_inp_hc3"],
          23 => ["Graphics/Pictures/", "ev_inp_hc4"],
          24 => ["Graphics/Pictures/", "ev_inp_hg1"],
          25 => ["Graphics/Pictures/", "ev_inp_hg2"],
          26 => ["Graphics/Pictures/", "ev_inp_hg3"],
          27 => ["Graphics/Pictures/", "ev_inp_hg4"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
          [24],
          [25],
          [26],
          [27],
        ],
      },
    57 => { # インプ
        :regist => {
          1 => ["Graphics/Pictures/", "80_inp_st21"],
          2 => ["Graphics/Pictures/", "ev_inp_ct21"],
          3 => ["Graphics/Pictures/", "ev_inp_ct22"],
          4 => ["Graphics/Pictures/", "ev_inp_hf1"],
          5 => ["Graphics/Pictures/", "ev_inp_hf2"],
          6 => ["Graphics/Pictures/", "ev_inp_hf3"],
          7 => ["Graphics/Pictures/", "ev_inp_hf4"],
        },
        # 表示パターンの指定
        :draw => [
          [1, 2],
          [1, 3],
          [4],
          [5],
          [6],
          [7],
        ],
      },
    58 => { # インプ
        :regist => {
          1 => ["Graphics/Pictures/", "80_inp_st11"],
          2 => ["Graphics/Pictures/", "ev_inp_ct11"],
          3 => ["Graphics/Pictures/", "ev_inp_ct12"],
          4 => ["Graphics/Pictures/", "ev_inp_hf1"],
          5 => ["Graphics/Pictures/", "ev_inp_hf2"],
          6 => ["Graphics/Pictures/", "ev_inp_hf3"],
          7 => ["Graphics/Pictures/", "ev_inp_hf4"],
        },
        # 表示パターンの指定
        :draw => [
          [1, 2],
          [1, 3],
          [4],
          [5],
          [6],
          [7],
        ],
      },
    59 => { # マンドラゴラ娘
        :regist => {
          1 => ["Graphics/Pictures/", "80_mdg_st01"],
          2 => ["Graphics/Pictures/", "ev_mdg_ct11"],
          3 => ["Graphics/Pictures/", "ev_mdg_ct12"],
          4 => ["Graphics/Pictures/", "ev_mdg_ct13"],
        },
        # 表示パターンの指定
        :draw => [
          [1, 2],
          [1, 3],
          [1, 4],
        ],
      },
    66 => { # ヴァンパイアガール
        :regist => {
          1 => ["Graphics/Pictures/", "ev_vgirl_ct01"],
          2 => ["Graphics/Pictures/", "ev_vgirl_ct02"],
          3 => ["Graphics/Pictures/", "ev_vgirl_ct03"],
          4 => ["Graphics/Pictures/", "ev_vgirl_ct04"],
          5 => ["Graphics/Pictures/", "ev_vgirl_ct05"],
          6 => ["Graphics/Pictures/", "ev_vgirl_ct06"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
        ],
      },
    70 => { # ネズミ娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_nezumi_ha1"],
          2 => ["Graphics/Pictures/", "ev_nezumi_ha2"],
          3 => ["Graphics/Pictures/", "ev_nezumi_ha3"],
          4 => ["Graphics/Pictures/", "ev_nezumi_hb1"],
          5 => ["Graphics/Pictures/", "ev_nezumi_hb2"],
          6 => ["Graphics/Pictures/", "ev_nezumi_hb3"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
        ],
      },
    72 => { # フェニックス娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_phoenix_ha1"],
          2 => ["Graphics/Pictures/", "ev_phoenix_ha2"],
          3 => ["Graphics/Pictures/", "ev_phoenix_ha3"],
          4 => ["Graphics/Pictures/", "ev_phoenix_ha4"],
          5 => ["Graphics/Pictures/", "ev_phoenix_ha5"],
          6 => ["Graphics/Pictures/", "ev_phoenix_ha6"],
          7 => ["Graphics/Pictures/", "ev_phoenix_ha7"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
        ],
      },
    74 => { # ウサギ娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_usagi_ha1"],
          2 => ["Graphics/Pictures/", "ev_usagi_ha2"],
          3 => ["Graphics/Pictures/", "ev_usagi_ha3"],
          4 => ["Graphics/Pictures/", "ev_usagi_ha4"],
          5 => ["Graphics/Pictures/", "ev_usagi_hc1"],
          6 => ["Graphics/Pictures/", "ev_usagi_hc2"],
          7 => ["Graphics/Pictures/", "ev_usagi_hc3"],
          8 => ["Graphics/Pictures/", "ev_usagi_hc4"],
          9 => ["Graphics/Pictures/", "ev_usagi_hc5"],
          10 => ["Graphics/Pictures/", "ev_usagi_hc6"],
          11 => ["Graphics/Pictures/", "ev_usagi_hc7"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
        ],
      },
    76 => { # シュリー
        :regist => {
          1 => ["Graphics/Pictures/", "ev_syuree_hc01"],
          2 => ["Graphics/Pictures/", "ev_syuree_hc02"],
          3 => ["Graphics/Pictures/", "ev_syuree_hc03"],
          4 => ["Graphics/Pictures/", "ev_syuree_hc04"],
          5 => ["Graphics/Pictures/", "ev_syuree_hc05"],
          6 => ["Graphics/Pictures/", "ev_syuree_hc06"],
          7 => ["Graphics/Pictures/", "ev_syuree_hc07"],
          8 => ["Graphics/Pictures/", "ev_syuree_hc08"],
          9 => ["Graphics/Pictures/", "ev_syuree_hc09"],
          10 => ["Graphics/Pictures/", "ev_syuree_hc10"],
          11 => ["Graphics/Pictures/", "ev_syuree_hc11"],
          12 => ["Graphics/Pictures/", "ev_syuree_hc12"],
          13 => ["Graphics/Pictures/", "ev_syuree_hc13"],
          14 => ["Graphics/Pictures/", "ev_syuree_hc14"],
          15 => ["Graphics/Pictures/", "ev_syuree_hc15"],
          16 => ["Graphics/Pictures/", "ev_syuree_hc16"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
        ],
      },
    77 => { # ジェイド
        :regist => {
          1 => ["Graphics/Pictures/", "ev_jeid_hb01"],
          2 => ["Graphics/Pictures/", "ev_jeid_hb02"],
          3 => ["Graphics/Pictures/", "ev_jeid_hb03"],
          4 => ["Graphics/Pictures/", "ev_jeid_hb04"],
          5 => ["Graphics/Pictures/", "ev_jeid_hb05"],
          6 => ["Graphics/Pictures/", "ev_jeid_hb06"],
          7 => ["Graphics/Pictures/", "ev_jeid_hb07"],
          8 => ["Graphics/Pictures/", "ev_jeid_hb08"],
          9 => ["Graphics/Pictures/", "ev_jeid_hb09"],
          10 => ["Graphics/Pictures/", "ev_jeid_hb10"],
          11 => ["Graphics/Pictures/", "ev_jeid_hb11"],
          12 => ["Graphics/Pictures/", "ev_jeid_hb12"],
          13 => ["Graphics/Pictures/", "ev_jeid_hb13"],
          14 => ["Graphics/Pictures/", "ev_jeid_hb14"],
          15 => ["Graphics/Pictures/", "ev_jeid_hb15"],
          16 => ["Graphics/Pictures/", "ev_jeid_hb16"],
          17 => ["Graphics/Pictures/", "ev_jeid_hb17"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
        ],
      },
    79 => { # ヌルコ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_nuruko_hb1"],
          2 => ["Graphics/Pictures/", "ev_nuruko_hb2"],
          3 => ["Graphics/Pictures/", "ev_nuruko_hb3"],
          4 => ["Graphics/Pictures/", "ev_nuruko_hb4"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
        ],
      },
    85 => { # ハイスラッグ娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_highslag_ha1"],
          2 => ["Graphics/Pictures/", "ev_highslag_ha2"],
          3 => ["Graphics/Pictures/", "ev_highslag_ha3"],
          4 => ["Graphics/Pictures/", "ev_highslag_hc05"],
          5 => ["Graphics/Pictures/", "ev_highslag_hc06"],
          6 => ["Graphics/Pictures/", "ev_highslag_hc07"],
          7 => ["Graphics/Pictures/", "ev_highslag_hc08"],
          8 => ["Graphics/Pictures/", "ev_highslag_hc09"],
          9 => ["Graphics/Pictures/", "ev_highslag_hc10"],
          10 => ["Graphics/Pictures/", "ev_highslag_hc11"],
          11 => ["Graphics/Pictures/", "ev_highslag_hc12"],
          12 => ["Graphics/Pictures/", "ev_highslag_hc13"],
          13 => ["Graphics/Pictures/", "ev_highslag_hc14"],
          14 => ["Graphics/Pictures/", "ev_highslag_hc15"],
          15 => ["Graphics/Pictures/", "ev_highslag_hc16"],
          16 => ["Graphics/Pictures/", "ev_highslag_hc17"],
          17 => ["Graphics/Pictures/", "ev_highslag_hc18"],
          18 => ["Graphics/Pictures/", "ev_highslag_hc19"],
          19 => ["Graphics/Pictures/", "ev_highslag_hc20"],
          20 => ["Graphics/Pictures/", "ev_highslag_hc21"],
          21 => ["Graphics/Pictures/", "ev_highslag_hc22"],
          22 => ["Graphics/Pictures/", "ev_highslag_hc23"],
          23 => ["Graphics/Pictures/", "ev_highslag_hc24"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
        ],
      },
    86 => { # ナメクジシスター
        :regist => {
          1 => ["Graphics/Pictures/", "ev_name_s_hc1"],
          2 => ["Graphics/Pictures/", "ev_name_s_hc2"],
          3 => ["Graphics/Pictures/", "ev_name_s_hc3"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
        ],
      },
    87 => { # スラグスターズ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_name2_hb01"],
          2 => ["Graphics/Pictures/", "ev_name2_hb02"],
          3 => ["Graphics/Pictures/", "ev_name2_hb03"],
          4 => ["Graphics/Pictures/", "ev_name2_hb04"],
          5 => ["Graphics/Pictures/", "ev_name2_hb05"],
          6 => ["Graphics/Pictures/", "ev_name2_hb06"],
          7 => ["Graphics/Pictures/", "ev_name2_hb07"],
          8 => ["Graphics/Pictures/", "ev_name2_hb08"],
          9 => ["Graphics/Pictures/", "ev_name2_hb09"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
        ],
      },
    93 => { # ライオット
        :regist => {
          1 => ["Graphics/Pictures/", "ev_liot_hb01"],
          2 => ["Graphics/Pictures/", "ev_liot_hb02"],
          3 => ["Graphics/Pictures/", "ev_liot_hb03"],
          4 => ["Graphics/Pictures/", "ev_liot_hb04"],
          5 => ["Graphics/Pictures/", "ev_liot_hb05"],
          6 => ["Graphics/Pictures/", "ev_liot_hb06"],
          7 => ["Graphics/Pictures/", "ev_liot_hb07"],
          8 => ["Graphics/Pictures/", "ev_liot_hb08"],
          9 => ["Graphics/Pictures/", "ev_liot_hb09"],
          10 => ["Graphics/Pictures/", "ev_liot_hb10"],
          11 => ["Graphics/Pictures/", "ev_liot_hb11"],
          12 => ["Graphics/Pictures/", "ev_liot_hb12"],
          13 => ["Graphics/Pictures/", "ev_liot_hb13"],
          14 => ["Graphics/Pictures/", "ev_liot_hb14"],
          15 => ["Graphics/Pictures/", "ev_liot_hb15"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
        ],
      },
    104 => { # クモ娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_kumo_ha1"],
          2 => ["Graphics/Pictures/", "ev_kumo_ha2"],
          3 => ["Graphics/Pictures/", "ev_kumo_ha3"],
          4 => ["Graphics/Pictures/", "ev_kumo_ha4"],
          5 => ["Graphics/Pictures/", "ev_kumo_ha5"],
          6 => ["Graphics/Pictures/", "ev_kumo_ha6"],
          7 => ["Graphics/Pictures/", "ev_kumo_hc1"],
          8 => ["Graphics/Pictures/", "ev_kumo_hc2"],
          9 => ["Graphics/Pictures/", "ev_kumo_hc3"],
          10 => ["Graphics/Pictures/", "ev_kumo_hc4"],
          11 => ["Graphics/Pictures/", "ev_kumo_hc5"],
          12 => ["Graphics/Pictures/", "ev_kumo_hc6"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
        ],
      },
    106 => { # 七尾
        :regist => {
          1 => ["Graphics/Pictures/", "ev_nanabi_h5"],
          2 => ["Graphics/Pictures/", "ev_nanabi_h6"],
          3 => ["Graphics/Pictures/", "ev_nanabi_h7"],
          4 => ["Graphics/Pictures/", "ev_nanabi_h8"],
          5 => ["Graphics/Pictures/", "ev_nanabi_h9"],
          6 => ["Graphics/Pictures/", "ev_nanabi_ctc01"],
          7 => ["Graphics/Pictures/", "ev_nanabi_ctc02"],
          8 => ["Graphics/Pictures/", "ev_nanabi_ctc03"],
          9 => ["Graphics/Pictures/", "ev_nanabi_ctc04"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2, 6],
          [3, 7],
          [4, 8],
          [5, 9],
        ],
      },
    109 => { # カニ娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_kani_h1"],
          2 => ["Graphics/Pictures/", "ev_kani_h2"],
          3 => ["Graphics/Pictures/", "ev_kani_ct21"],
          4 => ["Graphics/Pictures/", "ev_kani_ct22"],
          5 => ["Graphics/Pictures/", "ev_kani_ct23"],
          6 => ["Graphics/Pictures/", "ev_kani_ct24"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [1, 3],
          [2, 4],
          [2, 5],
          [2, 6],
        ],
      },
    113 => { # ラミア
        :regist => {
          1 => ["Graphics/Pictures/", "ev_lamia_ha1"],
          2 => ["Graphics/Pictures/", "ev_lamia_ha2"],
          3 => ["Graphics/Pictures/", "ev_lamia_ha3"],
          4 => ["Graphics/Pictures/", "ev_lamia_ha4"],
          5 => ["Graphics/Pictures/", "ev_lamia_ha5"],
          6 => ["Graphics/Pictures/", "ev_lamia_ha6"],
          7 => ["Graphics/Pictures/", "ev_lamia_ha7"],
          8 => ["Graphics/Pictures/", "ev_lamia_ha8"],
          9 => ["Graphics/Pictures/", "ev_lamia_hb1"],
          10 => ["Graphics/Pictures/", "ev_lamia_hb2"],
          11 => ["Graphics/Pictures/", "ev_lamia_hb3"],
          12 => ["Graphics/Pictures/", "ev_lamia_ctb01"],
          13 => ["Graphics/Pictures/", "ev_lamia_ctb02"],
          14 => ["Graphics/Pictures/", "ev_lamia_ctb03"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [9, 12],
          [10, 13],
          [11, 14],
        ],
      },
    121 => { # 65537ページ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_page65537_h1b"],
          2 => ["Graphics/Pictures/", "ev_page65537_h2b"],
          3 => ["Graphics/Pictures/", "ev_page65537_h3b"],
          4 => ["Graphics/Pictures/", "ev_page65537_h1c"],
          5 => ["Graphics/Pictures/", "ev_page65537_h2c"],
          6 => ["Graphics/Pictures/", "ev_page65537_h3c"],
          7 => ["Graphics/Pictures/", "ev_page65537_ct01"],
          8 => ["Graphics/Pictures/", "ev_page65537_ct02"],
          9 => ["Graphics/Pictures/", "ev_page65537_ct03"],
        },
        # 表示パターンの指定
        :draw => [
          [1, 7],
          [2, 8],
          [3, 9],
          [4, 7],
          [5, 8],
          [6, 9],
        ],
      },
    122 => { # シスターラミア
        :regist => {
          1 => ["Graphics/Pictures/", "ev_sisterlamia_hb1"],
          2 => ["Graphics/Pictures/", "ev_sisterlamia_hb2"],
          3 => ["Graphics/Pictures/", "ev_sisterlamia_hb3"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
        ],
      },
    127 => { # リトルバグ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_littlebug_hb01"],
          2 => ["Graphics/Pictures/", "ev_littlebug_hb02"],
          3 => ["Graphics/Pictures/", "ev_littlebug_hb03"],
          4 => ["Graphics/Pictures/", "ev_littlebug_hb04"],
          5 => ["Graphics/Pictures/", "ev_littlebug_hb05"],
          6 => ["Graphics/Pictures/", "ev_littlebug_hb06"],
          7 => ["Graphics/Pictures/", "ev_littlebug_hb07"],
          8 => ["Graphics/Pictures/", "ev_littlebug_hb08"],
          9 => ["Graphics/Pictures/", "ev_littlebug_hb09"],
          10 => ["Graphics/Pictures/", "ev_littlebug_hb10"],
          11 => ["Graphics/Pictures/", "ev_littlebug_hb11"],
          12 => ["Graphics/Pictures/", "ev_littlebug_hb12"],
          13 => ["Graphics/Pictures/", "ev_littlebug_hb13"],
          14 => ["Graphics/Pictures/", "ev_littlebug_hb14"],
          15 => ["Graphics/Pictures/", "ev_littlebug_hb15"],
          16 => ["Graphics/Pictures/", "ev_littlebug_hb16"],
          17 => ["Graphics/Pictures/", "ev_littlebug_hb17"],
          18 => ["Graphics/Pictures/", "ev_littlebug_hb18"],
          19 => ["Graphics/Pictures/", "ev_littlebug_hb19"],
          20 => ["Graphics/Pictures/", "ev_littlebug_hb20"],
          21 => ["Graphics/Pictures/", "ev_littlebug_hb21"],
          22 => ["Graphics/Pictures/", "ev_littlebug_hb22"],
          23 => ["Graphics/Pictures/", "ev_littlebug_hb23"],
          24 => ["Graphics/Pictures/", "ev_littlebug_hb24"],
          25 => ["Graphics/Pictures/", "ev_littlebug_hb25"],
          26 => ["Graphics/Pictures/", "ev_littlebug_hb26"],
          27 => ["Graphics/Pictures/", "ev_littlebug_hb27"],
          28 => ["Graphics/Pictures/", "ev_littlebug_hb28"],
          29 => ["Graphics/Pictures/", "ev_littlebug_hb29"],
          30 => ["Graphics/Pictures/", "ev_littlebug_hb30"],
          31 => ["Graphics/Pictures/", "ev_littlebug_hb31"],
          32 => ["Graphics/Pictures/", "ev_littlebug_hb32"],
          33 => ["Graphics/Pictures/", "ev_littlebug_hb33"],
          34 => ["Graphics/Pictures/", "ev_littlebug_hb34"],
          35 => ["Graphics/Pictures/", "ev_littlebug_hb35"],
          36 => ["Graphics/Pictures/", "ev_littlebug_hb36"],
          37 => ["Graphics/Pictures/", "ev_littlebug_hb37"],
          38 => ["Graphics/Pictures/", "ev_littlebug_hb39"],
          39 => ["Graphics/Pictures/", "ev_littlebug_hb40"],
          40 => ["Graphics/Pictures/", "ev_littlebug_hb41"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
          [24],
          [25],
          [26],
          [27],
          [28],
          [29],
          [30],
          [31],
          [32],
          [33],
          [34],
          [35],
          [36],
          [37],
          [38],
          [39],
          [40],
        ],
      },
    129 => { # ヒルデ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_brunhild_hb01"],
          2 => ["Graphics/Pictures/", "ev_brunhild_hb02"],
          3 => ["Graphics/Pictures/", "ev_brunhild_hb03"],
          4 => ["Graphics/Pictures/", "ev_brunhild_hb04"],
          5 => ["Graphics/Pictures/", "ev_brunhild_hb05"],
          6 => ["Graphics/Pictures/", "ev_brunhild_hb06"],
          7 => ["Graphics/Pictures/", "ev_brunhild_hb07"],
          8 => ["Graphics/Pictures/", "ev_brunhild_hb08"],
          9 => ["Graphics/Pictures/", "ev_brunhild_hb09"],
          10 => ["Graphics/Pictures/", "ev_brunhild_hb10"],
          11 => ["Graphics/Pictures/", "ev_brunhild_hb11"],
          12 => ["Graphics/Pictures/", "ev_brunhild_hb12"],
          13 => ["Graphics/Pictures/", "ev_brunhild_hb13"],
          14 => ["Graphics/Pictures/", "ev_brunhild_hb14"],
          15 => ["Graphics/Pictures/", "ev_brunhild_hb15"],
          16 => ["Graphics/Pictures/", "ev_brunhild_hb16"],
          17 => ["Graphics/Pictures/", "ev_brunhild_hb17"],
          18 => ["Graphics/Pictures/", "ev_brunhild_hb18"],
          19 => ["Graphics/Pictures/", "ev_brunhild_hb19"],
          20 => ["Graphics/Pictures/", "ev_brunhild_hb20"],
          21 => ["Graphics/Pictures/", "ev_brunhild_hb21"],
          22 => ["Graphics/Pictures/", "ev_brunhild_hb22"],
          23 => ["Graphics/Pictures/", "ev_brunhild_hb23"],
          24 => ["Graphics/Pictures/", "ev_brunhild_hb24"],
          25 => ["Graphics/Pictures/", "ev_brunhild_hc01"],
          26 => ["Graphics/Pictures/", "ev_brunhild_hc02"],
          27 => ["Graphics/Pictures/", "ev_brunhild_hc03"],
          28 => ["Graphics/Pictures/", "ev_brunhild_hc04"],
          29 => ["Graphics/Pictures/", "ev_brunhild_hc05"],
          30 => ["Graphics/Pictures/", "ev_brunhild_hc06"],
          31 => ["Graphics/Pictures/", "ev_brunhild_hc07"],
          32 => ["Graphics/Pictures/", "ev_brunhild_hc08"],
          33 => ["Graphics/Pictures/", "ev_brunhild_hc09"],
          34 => ["Graphics/Pictures/", "ev_brunhild_hc10"],
          35 => ["Graphics/Pictures/", "ev_brunhild_hc11"],
          36 => ["Graphics/Pictures/", "ev_brunhild_hc12"],
          37 => ["Graphics/Pictures/", "ev_brunhild_hc13"],
          38 => ["Graphics/Pictures/", "ev_brunhild_hc14"],
          39 => ["Graphics/Pictures/", "ev_brunhild_hc15"],
          40 => ["Graphics/Pictures/", "ev_brunhild_hc16"],
          41 => ["Graphics/Pictures/", "ev_brunhild_hc17"],
          42 => ["Graphics/Pictures/", "ev_brunhild_hc18"],
          43 => ["Graphics/Pictures/", "ev_brunhild_hc19"],
          44 => ["Graphics/Pictures/", "ev_brunhild_hc20"],
          45 => ["Graphics/Pictures/", "ev_brunhild_hc21"],
          46 => ["Graphics/Pictures/", "ev_brunhild_hc22"],
          47 => ["Graphics/Pictures/", "ev_brunhild_hc23"],
          48 => ["Graphics/Pictures/", "ev_brunhild_hc24"],
          49 => ["Graphics/Pictures/", "ev_brunhild_hc25"],
          50 => ["Graphics/Pictures/", "ev_brunhild_hc26"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
          [24],
          [25],
          [26],
          [27],
          [28],
          [29],
          [30],
          [31],
          [32],
          [33],
          [34],
          [35],
          [36],
          [37],
          [38],
          [39],
          [40],
          [41],
          [42],
          [43],
          [44],
          [45],
          [46],
          [47],
          [48],
          [49],
          [50],
        ],
      },
    131 => { # 呪いの人形娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_doll_hc01"],
          2 => ["Graphics/Pictures/", "ev_doll_hc02"],
          3 => ["Graphics/Pictures/", "ev_doll_hc03"],
          4 => ["Graphics/Pictures/", "ev_doll_hc04"],
          5 => ["Graphics/Pictures/", "ev_doll_hc05"],
          6 => ["Graphics/Pictures/", "ev_doll_hc06"],
          7 => ["Graphics/Pictures/", "ev_doll_hc07"],
          8 => ["Graphics/Pictures/", "ev_doll_hc08"],
          9 => ["Graphics/Pictures/", "ev_doll_hc09"],
          10 => ["Graphics/Pictures/", "ev_doll_hc10"],
          11 => ["Graphics/Pictures/", "ev_doll_hc11"],
          12 => ["Graphics/Pictures/", "ev_doll_hc12"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
        ],
      },
    134 => { # クロム
        :regist => {
          1 => ["Graphics/Pictures/", "ev_chrom_he01"],
          2 => ["Graphics/Pictures/", "ev_chrom_he02"],
          3 => ["Graphics/Pictures/", "ev_chrom_he03"],
          4 => ["Graphics/Pictures/", "ev_chrom_he04"],
          5 => ["Graphics/Pictures/", "ev_chrom_he05"],
          6 => ["Graphics/Pictures/", "ev_chrom_he06"],
          7 => ["Graphics/Pictures/", "ev_chrom_he07"],
          8 => ["Graphics/Pictures/", "ev_chrom_he08"],
          9 => ["Graphics/Pictures/", "ev_chrom_he09"],
          10 => ["Graphics/Pictures/", "ev_chrom_he10"],
          11 => ["Graphics/Pictures/", "ev_chrom_he11"],
          12 => ["Graphics/Pictures/", "ev_chrom_he12"],
          13 => ["Graphics/Pictures/", "ev_chrom_he13"],
          14 => ["Graphics/Pictures/", "ev_chrom_he14"],
          15 => ["Graphics/Pictures/", "ev_chrom_he15"],
          16 => ["Graphics/Pictures/", "ev_chrom_he16"],
          17 => ["Graphics/Pictures/", "ev_chrom_hf1"],
          18 => ["Graphics/Pictures/", "ev_chrom_hf2"],
          19 => ["Graphics/Pictures/", "ev_chrom_hf3"],
          20 => ["Graphics/Pictures/", "ev_chrom_hf4"],
          21 => ["Graphics/Pictures/", "ev_chrom_hf5"],
          22 => ["Graphics/Pictures/", "ev_chrom_hf6"],
          23 => ["Graphics/Pictures/", "ev_chrom_hf7"],
          24 => ["Graphics/Pictures/", "ev_chrom_hf8"],
          25 => ["Graphics/Pictures/", "ev_chrom_hg1"],
          26 => ["Graphics/Pictures/", "ev_chrom_hg2"],
          27 => ["Graphics/Pictures/", "ev_chrom_hg3"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
          [24],
          [25],
          [26],
          [27],
        ],
      },
    135 => { # フレデリカ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_frederika_hb1"],
          2 => ["Graphics/Pictures/", "ev_frederika_hb2"],
          3 => ["Graphics/Pictures/", "ev_frederika_hb3"],
          4 => ["Graphics/Pictures/", "ev_frederika_hc1"],
          5 => ["Graphics/Pictures/", "ev_frederika_hc2"],
          6 => ["Graphics/Pictures/", "ev_frederika_hc3"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
        ],
      },
    142 => { # バナッチ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_bander_hc1"],
          2 => ["Graphics/Pictures/", "ev_bander_hc2"],
          3 => ["Graphics/Pictures/", "ev_bander_hc3"],
          4 => ["Graphics/Pictures/", "ev_bander_hc4"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
        ],
      },
    143 => { # エヴァ
        :regist => {
          1 => ["Graphics/Pictures/", "80_eva_st02"],
          2 => ["Graphics/Pictures/", "ev_eva_ct01"],
          3 => ["Graphics/Pictures/", "ev_eva_ct02"],
          4 => ["Graphics/Pictures/", "ev_eva_ct03"],
          5 => ["Graphics/Pictures/", "ev_eva_ct04"],
          6 => ["Graphics/Pictures/", "ev_eva_ct11"],
          7 => ["Graphics/Pictures/", "ev_eva_ct12"],
          8 => ["Graphics/Pictures/", "ev_eva_ct13"],
          9 => ["Graphics/Pictures/", "ev_eva_ct14"],
          10 => ["Graphics/Pictures/", "ev_eva_ct21"],
          11 => ["Graphics/Pictures/", "ev_eva_ct22"],
          12 => ["Graphics/Pictures/", "ev_eva_ct23"],
          13 => ["Graphics/Pictures/", "ev_eva_ct24"],
          14 => ["Graphics/Pictures/", "ev_eva_ct31"],
          15 => ["Graphics/Pictures/", "ev_eva_ct32"],
          16 => ["Graphics/Pictures/", "ev_eva_ct33"],
          17 => ["Graphics/Pictures/", "ev_eva_ct34"],
        },
        # 表示パターンの指定
        :draw => [
          [1, 2],
          [1, 3],
          [1, 4],
          [1, 5],
          [1, 6],
          [1, 7],
          [1, 8],
          [1, 9],
          [1, 10],
          [1, 11],
          [1, 12],
          [1, 13],
          [1, 14],
          [1, 15],
          [1, 16],
          [1, 17],
        ],
      },
    155 => { # サキ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_saki_hb01"],
          2 => ["Graphics/Pictures/", "ev_saki_hb02"],
          3 => ["Graphics/Pictures/", "ev_saki_hb03"],
          4 => ["Graphics/Pictures/", "ev_saki_hb04"],
          5 => ["Graphics/Pictures/", "ev_saki_hb05"],
          6 => ["Graphics/Pictures/", "ev_saki_hb06"],
          7 => ["Graphics/Pictures/", "ev_saki_hb07"],
          8 => ["Graphics/Pictures/", "ev_saki_hb08"],
          9 => ["Graphics/Pictures/", "ev_saki_hb09"],
          10 => ["Graphics/Pictures/", "ev_saki_hb10"],
          11 => ["Graphics/Pictures/", "ev_saki_hb11"],
          12 => ["Graphics/Pictures/", "ev_saki_hc01"],
          13 => ["Graphics/Pictures/", "ev_saki_hc02"],
          14 => ["Graphics/Pictures/", "ev_saki_hc03"],
          15 => ["Graphics/Pictures/", "ev_saki_hc04"],
          16 => ["Graphics/Pictures/", "ev_saki_hc05"],
          17 => ["Graphics/Pictures/", "ev_saki_hc06"],
          18 => ["Graphics/Pictures/", "ev_saki_hc07"],
          19 => ["Graphics/Pictures/", "ev_saki_hc08"],
          20 => ["Graphics/Pictures/", "ev_saki_hc09"],
          21 => ["Graphics/Pictures/", "ev_saki_hc10"],
          22 => ["Graphics/Pictures/", "ev_saki_hd1"],
          23 => ["Graphics/Pictures/", "ev_saki_hd2"],
          24 => ["Graphics/Pictures/", "ev_saki_hd3"],
          25 => ["Graphics/Pictures/", "ev_saki_hd4"],
          26 => ["Graphics/Pictures/", "ev_saki_he1"],
          27 => ["Graphics/Pictures/", "ev_saki_he2"],
          28 => ["Graphics/Pictures/", "ev_saki_he3"],
          29 => ["Graphics/Pictures/", "ev_saki_he4"],
          30 => ["Graphics/Pictures/", "ev_saki_he5"],
          31 => ["Graphics/Pictures/", "ev_saki_he6"],
          32 => ["Graphics/Pictures/", "ev_saki_he7"],
          33 => ["Graphics/Pictures/", "ev_saki_he8"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
          [24],
          [25],
          [26],
          [27],
          [28],
          [29],
          [30],
          [31],
          [32],
          [33],
        ],
      },
    156 => { # デビルファイター
        :regist => {
          1 => ["Graphics/Pictures/", "ev_d_fighter_ha01"],
          2 => ["Graphics/Pictures/", "ev_d_fighter_ha02"],
          3 => ["Graphics/Pictures/", "ev_d_fighter_ha03"],
          4 => ["Graphics/Pictures/", "ev_d_fighter_ha04"],
          5 => ["Graphics/Pictures/", "ev_d_fighter_ha05"],
          6 => ["Graphics/Pictures/", "ev_d_fighter_ha06"],
          7 => ["Graphics/Pictures/", "ev_d_fighter_ha07"],
          8 => ["Graphics/Pictures/", "ev_d_fighter_ha08"],
          9 => ["Graphics/Pictures/", "ev_d_fighter_ha09"],
          10 => ["Graphics/Pictures/", "ev_d_fighter_ha10"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
        ],
      },
    160 => { # ワームビレッジャ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_wormv_h1"],
          2 => ["Graphics/Pictures/", "ev_wormv_h4"],
          3 => ["Graphics/Pictures/", "ev_wormv_h5"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
        ],
      },
    163 => { # リリィ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_lily_h01"],
          2 => ["Graphics/Pictures/", "ev_lily_h02"],
          3 => ["Graphics/Pictures/", "ev_lily_h03"],
          4 => ["Graphics/Pictures/", "ev_lily_h04"],
          5 => ["Graphics/Pictures/", "ev_lily_h05"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
        ],
      },
    166 => { # ナーキュバス
        :regist => {
          1 => ["Graphics/Pictures/", "ev_narcubus_hb1"],
          2 => ["Graphics/Pictures/", "ev_narcubus_hb2"],
          3 => ["Graphics/Pictures/", "ev_narcubus_hb3"],
          4 => ["Graphics/Pictures/", "ev_narcubus_hb4"],
          5 => ["Graphics/Pictures/", "ev_narcubus_hc1"],
          6 => ["Graphics/Pictures/", "ev_narcubus_hc2"],
          7 => ["Graphics/Pictures/", "ev_narcubus_hc3"],
          8 => ["Graphics/Pictures/", "ev_narcubus_hc4"],
          9 => ["Graphics/Pictures/", "ev_narcubus_hc5"],
          10 => ["Graphics/Pictures/", "ev_narcubus_hc6"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
        ],
      },
    171 => { # リザードボス
        :regist => {
          1 => ["Graphics/Pictures/", "ev_lizardboss_hb1"],
          2 => ["Graphics/Pictures/", "ev_lizardboss_hb2"],
          3 => ["Graphics/Pictures/", "ev_lizardboss_hb3"],
          4 => ["Graphics/Pictures/", "ev_lizardboss_hb4"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
        ],
      },
    176 => { # ヴィタエ
        :regist => {
          1 => ["Graphics/Pictures/", "80_vitae_st02"],
          2 => ["Graphics/Pictures/", "ev_vitae_ct01"],
          3 => ["Graphics/Pictures/", "ev_vitae_ct02"],
          4 => ["Graphics/Pictures/", "ev_vitae_ct03"],
          5 => ["Graphics/Pictures/", "ev_vitae_ct04"],
          6 => ["Graphics/Pictures/", "ev_vitae_ct05"],
          7 => ["Graphics/Pictures/", "ev_vitae_ct06"],
        },
        # 表示パターンの指定
        :draw => [
          [1, 2],
          [1, 3],
          [1, 4],
          [1, 5],
          [1, 6],
          [1, 7],
        ],
      },
    177 => { # ヴェータラ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_vetala_hc01"],
          2 => ["Graphics/Pictures/", "ev_vetala_hc02"],
          3 => ["Graphics/Pictures/", "ev_vetala_hc03"],
          4 => ["Graphics/Pictures/", "ev_vetala_hc04"],
          5 => ["Graphics/Pictures/", "ev_vetala_hc05"],
          6 => ["Graphics/Pictures/", "ev_vetala_hc06"],
          7 => ["Graphics/Pictures/", "ev_vetala_hc07"],
          8 => ["Graphics/Pictures/", "ev_vetala_hc08"],
          9 => ["Graphics/Pictures/", "ev_vetala_hc09"],
          10 => ["Graphics/Pictures/", "ev_vetala_hc10"],
          11 => ["Graphics/Pictures/", "ev_vetala_hc11"],
          12 => ["Graphics/Pictures/", "ev_vetala_hc12"],
          13 => ["Graphics/Pictures/", "ev_vetala_hc13"],
          14 => ["Graphics/Pictures/", "ev_vetala_hc14"],
          15 => ["Graphics/Pictures/", "ev_vetala_hc15"],
          16 => ["Graphics/Pictures/", "ev_vetala_hc16"],
          17 => ["Graphics/Pictures/", "ev_vetala_hc17"],
          18 => ["Graphics/Pictures/", "ev_vetala_hc18"],
          19 => ["Graphics/Pictures/", "ev_vetala_hc19"],
          20 => ["Graphics/Pictures/", "ev_vetala_hc20"],
          21 => ["Graphics/Pictures/", "ev_vetala_hc21"],
          22 => ["Graphics/Pictures/", "ev_vetala_hc22"],
          23 => ["Graphics/Pictures/", "ev_vetala_hc23"],
          24 => ["Graphics/Pictures/", "ev_vetala_hc24"],
          25 => ["Graphics/Pictures/", "ev_vetala_hc25"],
          26 => ["Graphics/Pictures/", "ev_vetala_hc26"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
          [24],
          [25],
          [26],
        ],
      },
    178 => { # ヴァルト
        :regist => {
          1 => ["Graphics/Pictures/", "ev_valt_hb01"],
          2 => ["Graphics/Pictures/", "ev_valt_hb02"],
          3 => ["Graphics/Pictures/", "ev_valt_hb03"],
          4 => ["Graphics/Pictures/", "ev_valt_hb04"],
          5 => ["Graphics/Pictures/", "ev_valt_hb05"],
          6 => ["Graphics/Pictures/", "ev_valt_hb06"],
          7 => ["Graphics/Pictures/", "ev_valt_hb07"],
          8 => ["Graphics/Pictures/", "ev_valt_hb08"],
          9 => ["Graphics/Pictures/", "ev_valt_hb09"],
          10 => ["Graphics/Pictures/", "ev_valt_hb10"],
          11 => ["Graphics/Pictures/", "ev_valt_hb11"],
          12 => ["Graphics/Pictures/", "ev_valt_hb12"],
          13 => ["Graphics/Pictures/", "ev_valt_hb13"],
          14 => ["Graphics/Pictures/", "ev_valt_hb14"],
          15 => ["Graphics/Pictures/", "ev_valt_hb15"],
          16 => ["Graphics/Pictures/", "ev_valt_hb16"],
          17 => ["Graphics/Pictures/", "ev_valt_hb17"],
          18 => ["Graphics/Pictures/", "ev_valt_hb18"],
          19 => ["Graphics/Pictures/", "ev_valt_hb19"],
          20 => ["Graphics/Pictures/", "ev_valt_hb20"],
          21 => ["Graphics/Pictures/", "ev_valt_hb21"],
          22 => ["Graphics/Pictures/", "ev_valt_hb22"],
          23 => ["Graphics/Pictures/", "ev_valt_hb23"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
        ],
      },
    184 => { # ジャンクドール娘
        :regist => {
          1 => ["Graphics/Pictures/", "ev_junkdoll_hb1"],
          2 => ["Graphics/Pictures/", "ev_junkdoll_hb2"],
          3 => ["Graphics/Pictures/", "ev_junkdoll_hb3"],
          4 => ["Graphics/Pictures/", "ev_junkdoll_hc1"],
          5 => ["Graphics/Pictures/", "ev_junkdoll_hc2"],
          6 => ["Graphics/Pictures/", "ev_junkdoll_hc3"],
          7 => ["Graphics/Pictures/", "ev_junkdoll_hc4"],
          8 => ["Graphics/Pictures/", "ev_junkdoll_hc5"],
          9 => ["Graphics/Pictures/", "ev_junkdoll_hc6"],
          10 => ["Graphics/Pictures/", "ev_junkdoll_hc7"],
          11 => ["Graphics/Pictures/", "ev_junkdoll_hc8"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
        ],
      },
    185 => { # ラディオ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_radio_h01"],
          2 => ["Graphics/Pictures/", "ev_radio_h02"],
          3 => ["Graphics/Pictures/", "ev_radio_h03"],
          4 => ["Graphics/Pictures/", "ev_radio_h04"],
          5 => ["Graphics/Pictures/", "ev_radio_h05"],
          6 => ["Graphics/Pictures/", "ev_radio_h06"],
          7 => ["Graphics/Pictures/", "ev_radio_h07"],
          8 => ["Graphics/Pictures/", "ev_radio_h08"],
          9 => ["Graphics/Pictures/", "ev_radio_h09"],
          10 => ["Graphics/Pictures/", "ev_radio_h10"],
          11 => ["Graphics/Pictures/", "ev_radio_h11"],
          12 => ["Graphics/Pictures/", "ev_radio_h12"],
          13 => ["Graphics/Pictures/", "ev_radio_h13"],
          14 => ["Graphics/Pictures/", "ev_radio_h14"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
        ],
      },
    525 => { # ソニア
        :regist => {
          1 => ["Graphics/Pictures/", "ev_sonia_ha01"],
          2 => ["Graphics/Pictures/", "ev_sonia_ha02"],
          3 => ["Graphics/Pictures/", "ev_sonia_ha03"],
          4 => ["Graphics/Pictures/", "ev_sonia_ha04"],
          5 => ["Graphics/Pictures/", "ev_sonia_ha05"],
          6 => ["Graphics/Pictures/", "ev_sonia_ha06"],
          7 => ["Graphics/Pictures/", "ev_sonia_ha07"],
          8 => ["Graphics/Pictures/", "ev_sonia_ha08"],
          9 => ["Graphics/Pictures/", "ev_sonia_ha09"],
          10 => ["Graphics/Pictures/", "ev_sonia_ha10"],
          11 => ["Graphics/Pictures/", "ev_sonia_ha11"],
          12 => ["Graphics/Pictures/", "ev_sonia_ha12"],
          13 => ["Graphics/Pictures/", "ev_sonia_ha13"],
          14 => ["Graphics/Pictures/", "ev_sonia_ha14"],
          15 => ["Graphics/Pictures/", "ev_sonia_ha15"],
          16 => ["Graphics/Pictures/", "ev_sonia_ha16"],
          17 => ["Graphics/Pictures/", "ev_sonia_ha17"],
          18 => ["Graphics/Pictures/", "ev_sonia_ha18"],
          19 => ["Graphics/Pictures/", "ev_sonia_ha19"],
          20 => ["Graphics/Pictures/", "ev_sonia_ha20"],
          21 => ["Graphics/Pictures/", "ev_sonia_ha21"],
          22 => ["Graphics/Pictures/", "ev_sonia_hb01"],
          23 => ["Graphics/Pictures/", "ev_sonia_hb02"],
          24 => ["Graphics/Pictures/", "ev_sonia_hb03"],
          25 => ["Graphics/Pictures/", "ev_sonia_hb04"],
          26 => ["Graphics/Pictures/", "ev_sonia_hb05"],
          27 => ["Graphics/Pictures/", "ev_sonia_hb06"],
          28 => ["Graphics/Pictures/", "ev_sonia_hb07"],
          29 => ["Graphics/Pictures/", "ev_sonia_hb08"],
          30 => ["Graphics/Pictures/", "ev_sonia_hb09"],
          31 => ["Graphics/Pictures/", "ev_sonia_hb10"],
          32 => ["Graphics/Pictures/", "ev_sonia_hb11"],
          33 => ["Graphics/Pictures/", "ev_sonia_hb12"],
          34 => ["Graphics/Pictures/", "ev_sonia_hb13"],
          35 => ["Graphics/Pictures/", "ev_sonia_hb14"],
          36 => ["Graphics/Pictures/", "ev_sonia_hb15"],
          37 => ["Graphics/Pictures/", "ev_sonia_hb16"],
          38 => ["Graphics/Pictures/", "ev_sonia_hb17"],
          39 => ["Graphics/Pictures/", "ev_sonia_hb18"],
          40 => ["Graphics/Pictures/", "ev_sonia_hb19"],
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
          [8],
          [9],
          [10],
          [11],
          [12],
          [13],
          [14],
          [15],
          [16],
          [17],
          [18],
          [19],
          [20],
          [21],
          [22],
          [23],
          [24],
          [25],
          [26],
          [27],
          [28],
          [29],
          [30],
          [31],
          [32],
          [33],
          [34],
          [35],
          [36],
          [37],
          [38],
          [39],
          [40],
        ],
      },
    529 => { # サラ
        :regist => {
          1 => ["Graphics/Pictures/", "ev_sara_ha1"],
          2 => ["Graphics/Pictures/", "ev_sara_ha2"],
          3 => ["Graphics/Pictures/", "ev_sara_ha3"],
          4 => ["Graphics/Pictures/", "ev_sara_hb1"],
          5 => ["Graphics/Pictures/", "ev_sara_hb2"],
          6 => ["Graphics/Pictures/", "ev_sara_hb3"],
          7 => ["Graphics/Pictures/", "ev_sara_hb4"], 
        },
        # 表示パターンの指定
        :draw => [
          [1],
          [2],
          [3],
          [4],
          [5],
          [6],
          [7],
        ],
      },
  }

  # アクター画像の設定
  # パス,ファイル名,色相,X調整値,Y調整値,拡縮率で記述します。
  # X座標の基準点は中央,Y座標の基準点は最下部です。
  # X調整値に値が設定された時点で自動縮小機能がOFFになります。
  # 色相以降の設定値は省略可能です。(デフォルト値:色相=0,X調整値=0,Y調整値=0,拡縮率=1.00)
  ACTOR_IMAGE = {
    1 => ["Graphics/Pictures/", "80_ruka_st01",0,20,0,0.9],
    5 => ["Graphics/Pictures/", "80_alice_st71",0,0,0],
    12 => ["Graphics/Pictures/", "80_sylph_st01",0,0,-20,0.9],
    13 => ["Graphics/Pictures/", "80_gnome_st01",0,0,0,0.9],
    26 => ["Graphics/Pictures/", "80_iriasu_st31",0,0,0,0.8],
    41 => ["Graphics/Pictures/", "80_stein_st31",0,0,-20,0.9],
    53 => ["Graphics/Pictures/", "80_slime_st01",0,0,-30,0.9],
    54 => ["Graphics/Pictures/", "80_bunnyslime_st01",0,0,0,0.8],
    55 => ["Graphics/Pictures/", "80_name_st01",0,-30,-40,0.9],
    56 => ["Graphics/Pictures/", "80_inp_st01",0,0,-20,0.9],
    57 => ["Graphics/Pictures/", "80_inp_st21",0,0,-10,0.9],
    58 => ["Graphics/Pictures/", "80_inp_st11",0,0,-10,0.9],
    59 => ["Graphics/Pictures/", "80_mdg_st01",0,0,0,0.8],
    60 => ["Graphics/Pictures/", "80_dog_st01",0,0,-10,0.9],
    61 => ["Graphics/Pictures/", "80_mimizu_st01",0,0,0,0.8],
    62 => ["Graphics/Pictures/", "80_gob_st01",0,0,0,0.9],
    64 => ["Graphics/Pictures/", "80_pramia_st01",0,0,0,0.9],
    66 => ["Graphics/Pictures/", "80_vgirl_st01",0,0,0,0.9],
    68 => ["Graphics/Pictures/", "80_dragonp_st01",0,0,0,0.9],
    70 => ["Graphics/Pictures/", "80_nezumi_st01",0,-20,-20,0.9],
    71 => ["Graphics/Pictures/", "80_okami_st01",0,0,-20,0.9],
    72 => ["Graphics/Pictures/", "80_phoenix_st01",0,0,0,0.9],
    73 => ["Graphics/Pictures/", "80_hiru_st01",0,0,0,0.8],
    74 => ["Graphics/Pictures/", "80_usagi_st01",0,0,0,0.85],
    75 => ["Graphics/Pictures/", "80_hituzi_st01",0,0,-30,0.8],
    76 => ["Graphics/Pictures/", "80_syuree_st01",0,0,0,0.8],
    77 => ["Graphics/Pictures/", "80_jeid_st01",0,0,0,0.9],
    78 => ["Graphics/Pictures/", "80_syesta_st01",0,0,0,0.9],
    79 => ["Graphics/Pictures/", "80_nuruko_st01",0,0,-50,0.9],
    80 => ["Graphics/Pictures/", "80_orc_st01",0,40,-40],
    81 => ["Graphics/Pictures/", "80_mitubati_st01",0,0,0,0.8],
    82 => ["Graphics/Pictures/", "80_suzume_st01",0,0,0,0.8],
    83 => ["Graphics/Pictures/", "80_hapy_a_st01",0,0,0,0.9],
    84 => ["Graphics/Pictures/", "80_hapy_bc_st01",0,0,0,0.9],
    85 => ["Graphics/Pictures/", "80_highslag_st01",0,0,0,0.8],
    86 => ["Graphics/Pictures/", "80_name_s_st01",0,0,-30,0.9],
    87 => ["Graphics/Pictures/", "80_name2_st01",0,0,0,0.8],
    88 => ["Graphics/Pictures/", "80_jack_st01",0,-40,0,0.8],
    89 => ["Graphics/Pictures/", "80_ropa_st01",0,0,0,0.8],
    90 => ["Graphics/Pictures/", "80_meda_st01",0,0,-20,0.9],
    91 => ["Graphics/Pictures/", "80_candle_st01",0,0,-20,0.9],
    92 => ["Graphics/Pictures/", "80_eater_st01",0,0,-20,0.9],
    93 => ["Graphics/Pictures/", "80_liot_st01",0,0,-20,0.9],
    94 => ["Graphics/Pictures/", "80_luksl_st01",0,0,-20,0.9],
    95 => ["Graphics/Pictures/", "80_delh_a_st01",0,0,-20,0.9],
    96 => ["Graphics/Pictures/", "80_delh_b_st01",0,0,-20,0.9],
    97 => ["Graphics/Pictures/", "80_fairy_st01",0,0,-20,0.9],
    98 => ["Graphics/Pictures/", "80_minikani_st01",0,0,-20,0.9],
    99 => ["Graphics/Pictures/", "80_namazu_st01",0,0,-20,0.9],
    100 => ["Graphics/Pictures/", "80_rahure_st01",0,0,-20,0.9],
    101 => ["Graphics/Pictures/", "80_cent2_st01",0,0,-20,0.9],
    102 => ["Graphics/Pictures/", "80_youko_st01",0,0,-20,0.9],
    103 => ["Graphics/Pictures/", "80_kamuro_st01",0,0,-20,0.9],
    104 => ["Graphics/Pictures/", "80_kumo_st01",0,0,-20,0.9],
    105 => ["Graphics/Pictures/", "80_mimic_st01",0,0,-20,0.9],
    106 => ["Graphics/Pictures/", "80_nanabi_st01",0,0,-20,0.9],
    107 => ["Graphics/Pictures/", "80_namako_st01",0,0,-20,0.9],
    108 => ["Graphics/Pictures/", "80_kai_st01",0,0,-20,0.9],
    109 => ["Graphics/Pictures/", "80_kani_st01",0,0,-20,0.9],
    110 => ["Graphics/Pictures/", "80_slimelord_st01",0,0,0,0.7],
    111 => ["Graphics/Pictures/", "80_suika_st01",0,0,-20,0.9],
    112 => ["Graphics/Pictures/", "80_utubo_st01",0,0,-20,0.9],
    113 => ["Graphics/Pictures/", "80_lamia_st01",0,0,-20,0.9],
    114 => ["Graphics/Pictures/", "80_wakame_st01",0,0,-20,0.9],
    115 => ["Graphics/Pictures/", "80_kurage_st01",0,0,-20,0.9],
    116 => ["Graphics/Pictures/", "80_iso_st01",0,0,-20,0.9],
    117 => ["Graphics/Pictures/", "80_ankou_st01",0,0,-20,0.9],
    118 => ["Graphics/Pictures/", "80_meia_st01",0,0,-20,0.9],
    119 => ["Graphics/Pictures/", "80_page17_st01",0,0,-20,0.9],
    120 => ["Graphics/Pictures/", "80_page257_st01",0,0,-20,0.9],
    121 => ["Graphics/Pictures/", "80_page65537_st01",0,0,-20,0.9],
    122 => ["Graphics/Pictures/", "80_sisterlamia_st01",0,50,-20,0.9],
    123 => ["Graphics/Pictures/", "80_sisccubus_st01",0,0,-20,0.9],
    124 => ["Graphics/Pictures/", "80_arikui_st01",0,0,0,0.8],
    125 => ["Graphics/Pictures/", "80_grizzly_st01",0,0,-40],
    126 => ["Graphics/Pictures/", "80_XX-7_st01",0,0,0,0.8],
    127 => ["Graphics/Pictures/", "80_littlebug_st01",0,0,-20,0.9],
    128 => ["Graphics/Pictures/", "80_kaniloid_st01",0,0,-20,0.9],
    129 => ["Graphics/Pictures/", "80_brunhild_st01",0,0,-20,0.9],
    130 => ["Graphics/Pictures/", "80_ghost_st01",0,0,-20,0.9],
    131 => ["Graphics/Pictures/", "80_doll_st01",0,0,-20,0.9],
    132 => ["Graphics/Pictures/", "80_zonbe_st11",0,0,-20,0.9],
    133 => ["Graphics/Pictures/", "80_zonbe_st21",0,0,-20,0.9],
    134 => ["Graphics/Pictures/", "80_chrom_st21",0,0,-20,0.9],
    135 => ["Graphics/Pictures/", "80_frederika_st01",0,0,-20,0.9],
    136 => ["Graphics/Pictures/", "80_elf_st01",0,0,-20,0.9],
    137 => ["Graphics/Pictures/", "80_braunys_st01",0,0,-20,0.8],
    138 => ["Graphics/Pictures/", "80_tfairy_st01",0,0,-20,0.9],
    139 => ["Graphics/Pictures/", "80_fairys_st01",0,0,-20,0.9],
    140 => ["Graphics/Pictures/", "80_taran_st01",0,0,-20,0.9],
    141 => ["Graphics/Pictures/", "80_mino_st01",0,0,-20,0.9],
    142 => ["Graphics/Pictures/", "80_bander_st01",0,0,-20,0.9],
    143 => ["Graphics/Pictures/", "80_eva_st01",0,0,0,0.9],
    144 => ["Graphics/Pictures/", "80_saboresu_st01",0,0,-80],
    145 => ["Graphics/Pictures/", "80_mukade_st01",0,0,-20,0.9],
    146 => ["Graphics/Pictures/", "80_sasori_st01",0,0,-20,0.9],
    147 => ["Graphics/Pictures/", "80_saboten_st01",0,0,-20,0.9],
    148 => ["Graphics/Pictures/", "80_datyou_st01",0,80,-20,0.9],
    149 => ["Graphics/Pictures/", "80_lamp_st21",0,0,-20,0.9],
    150 => ["Graphics/Pictures/", "80_mummy_st01",0,0,-20,0.9],
    151 => ["Graphics/Pictures/", "80_kobura_st01",0,0,-20,0.9],
    152 => ["Graphics/Pictures/", "80_lamias_st01",0,0,-20,0.9],
    154 => ["Graphics/Pictures/", "80_wani_st01",0,0,-20,0.9],
    155 => ["Graphics/Pictures/", "80_saki_st01",0,0,-20,0.9],
    156 => ["Graphics/Pictures/", "80_d_fighter_st01",0,0,-20,0.9],
    157 => ["Graphics/Pictures/", "80_oogumo_st01",0,0,-20,0.8],
    158 => ["Graphics/Pictures/", "80_suckvore_st01",0,0,-20,0.9],
    159 => ["Graphics/Pictures/", "80_ironmaiden_st01",0,0,-20,0.9],
    160 => ["Graphics/Pictures/", "80_wormv_st01",0,0,-20,0.9],
    161 => ["Graphics/Pictures/", "80_ustrel_st01",0,0,-40,0.9],
    162 => ["Graphics/Pictures/", "80_mitutubo_st01",0,0,-20,0.9],
    163 => ["Graphics/Pictures/", "80_lily_st01",0,0,-20,0.9],
    164 => ["Graphics/Pictures/", "80_kooni_st01",0,0,-50],
    165 => ["Graphics/Pictures/", "80_onaho_st01",0,0,0,0.8],
    166 => ["Graphics/Pictures/", "80_narcubus_st11",0,0,-20,0.9],
    167 => ["Graphics/Pictures/", "80_lusia_st01",0,0,-20,0.9],
    168 => ["Graphics/Pictures/", "80_dodome_st01",0,0,-20,0.9],
    169 => ["Graphics/Pictures/", "80_lizardthief_st01",0,0,-40,0.9],
    170 => ["Graphics/Pictures/", "80_lizardthief_st11",0,0,-40,0.9],
    171 => ["Graphics/Pictures/", "80_lizardboss_st01",0,0,-20,0.9],
    172 => ["Graphics/Pictures/", "80_sinkiro_st01",0,0,-20,0.9],
    173 => ["Graphics/Pictures/", "80_arizigoku_st01",0,0,-20,0.9],
    174 => ["Graphics/Pictures/", "80_sandw_st01",0,30,-20,0.9],
    175 => ["Graphics/Pictures/", "80_d_scylla_st01",0,0,-20,0.9],
    176 => ["Graphics/Pictures/", "80_vitae_st01",0,0,-20,0.9],
    177 => ["Graphics/Pictures/", "80_vetala_st01",0,0,-20,0.9],
    178 => ["Graphics/Pictures/", "80_valt_st01",0,0,-20,0.9],
    179 => ["Graphics/Pictures/", "80_sinifa_st01",0,0,-20,0.9],
    180 => ["Graphics/Pictures/", "80_shadow_st01",0,0,-20,0.9],
    181 => ["Graphics/Pictures/", "80_gaistvine_st01",0,0,-20,0.9],
    182 => ["Graphics/Pictures/", "80_c_homunculus_st01",0,0,-20,0.9],
    183 => ["Graphics/Pictures/", "80_ironmaiden_k_st01",0,0,-20,0.9],
    184 => ["Graphics/Pictures/", "80_junkdoll_st01",0,0,-20,0.9],
    185 => ["Graphics/Pictures/", "80_radio_st01",0,0,-20,0.8],
    525 => ["Graphics/Pictures/", "80_sonia_s1_st01",0,0,-70],
    529 => ["Graphics/Pictures/", "80_sara_st01",0,0,-20,0.9],
    531 => ["Graphics/Pictures/", "80_saniria_st12",0,0,-20,0.9],
    533 => ["Graphics/Pictures/", "80_grandnoa_st01",0,0,-20,0.9],
    540 => ["Graphics/Pictures/", "80_amira_st01",0,0,-20,0.9],
    541 => ["Graphics/Pictures/", "80_piha_st01",0,0,-20,0.9],
    542 => ["Graphics/Pictures/", "80_domeima_st01",0,-70,-20,0.9],
    544 => ["Graphics/Pictures/", "80_mob_maid_st01",0,0,-20,0.9],
    545 => ["Graphics/Pictures/", "80_mob_murabito1_st01",0,0,-20,0.9],
    546 => ["Graphics/Pictures/", "80_mob_hurou_st01",0,0,-20,0.9],
    547 => ["Graphics/Pictures/", "80_dondaria_st01",0,0,-20,0.9],
    548 => ["Graphics/Pictures/", "80_mob_bunny1_st01",0,0,-20,0.9],
    549 => ["Graphics/Pictures/", "80_mob_touzoku_st01",0,0,-20,0.9],
    550 => ["Graphics/Pictures/", "80_mob_kakutou_st01",0,0,-20,0.9],
    551 => ["Graphics/Pictures/", "80_mob_maid1_st01",0,0,-20,0.9],
    552 => ["Graphics/Pictures/", "80_mob_elf1_st01",0,0,-20,0.9],
    553 => ["Graphics/Pictures/", "80_mob_gakusya1_st01",0,0,-20,0.9],
    554 => ["Graphics/Pictures/", "80_mob_nasu1_st01",0,0,-20,0.9],
    555 => ["Graphics/Pictures/", "80_mob_murabito2_st01",0,0,-20,0.9],
    556 => ["Graphics/Pictures/", "80_mob_sister1_st01",0,0,-20,0.9],
    557 => ["Graphics/Pictures/", "80_justice_st01",0,0,-20,0.9],
    558 => ["Graphics/Pictures/", "80_mob_uranai1_st01",0,0,-20,0.9],
    559 => ["Graphics/Pictures/", "80_mob_assasin1_st01",0,0,-20,0.9],
    560 => ["Graphics/Pictures/", "80_mob_odoriko1_st01",0,0,-20,0.9],
    561 => ["Graphics/Pictures/", "80_mob_majyo1_st01",0,0,-20,0.9],
    562 => ["Graphics/Pictures/", "80_mob_bukiya1_st01",0,0,-20,0.9],
  }
  # アクター固有アビリティの設定
  FIX_ABILITY_NAME = "固有アビリティ:"
  ACTOR_FIX_ABILITY = {
    1 => ["勇者の血統",
      "「剣技」「勇者技」を使用可能",
      "「勇者技」の威力がアップ",
    ],
    5 => ["プチまおう",
      "「黒魔法」「闇技」「魔技」を使用可能",
      "闇属性スキルを使用した際のHP消費が半減",
    ],
    12 => ["風の精霊",
      "風属性攻撃の威力がアップ",
      "「盗賊技」「自然感応」を使用可能",
      "瀕死になると「風の極み」が発動する",
    ],
    13 => ["土の精霊",
      "土属性攻撃の威力がアップ",
      "「棍技」「格闘」「自然感応」を使用可能",
      "「格闘」の威力が攻撃力にのみ依存する",
      "瀕死になると「荒ぶる大地」が発動する",
    ],
    26 => ["そうせいのめがみ",
      "「白魔法」「聖技」を使用可能",
      "聖属性スキルを使用した際の消費MPが半減",
    ],
    41 => ["マッドサイエンジェル",
      "「魔導科学」「医術」を使用可能",
      "「魔導科学」の威力がアップ",
    ],
    53 => ["ブーメランだいすき",
      "ブーメランを装備可能",
      "「投擲技」を使用可能",
      "「投擲技」の威力がアップ",
    ],
    54 => ["自称うさぎ",
      "「獣技」を使用可能",
      "素早さが30%アップ",
    ],
    55 => ["ヌルヌルなめくじ",
      "通常攻撃で頻繁にヌルヌルにする",
      "すでにヌルヌルなので状態異常「ヌルヌル」にならない",
      "「ドレス」「薄着」が装備でき、おめかし可能",
    ],
    56 => ["インプの火遊び",
      "「黒魔法」を使用可能",
      "火属性攻撃の威力がアップ",
      "「黒魔法」の消費MPが2/3になる",
    ],
    57 => ["かくとうインプ",
      "「格闘」を使用可能",
      "「格闘」の威力が少しアップ",
    ],
    58 => ["おどおどインプ",
      "「白魔法」を使用可能",
      "敵に狙われる確率がやや低い",
      "瀕死になると回避率が大幅にアップ",
    ],
    59 => ["マンドラゴラハート",
      "通常攻撃で麻痺させる事がある",
      "「歌う」の状態異常発生率がアップ",
      "音波属性を無効にし、状態異常「麻痺」「混乱」にならない",
    ],
    60 => ["わんわんぐるる",
      "通常攻撃で威嚇し、スタンさせる事がある",
      "通常攻撃が素早く発動する",
      "状態異常「スタン」にならない",
      "ターン終了時に「あなほり」をする事がある",
    ],
    61 => ["ネバネバみみず",
      "「蛇技」を使用可能",
      "通常攻撃で頻繁にヌルヌルにする",
      "すでにヌルヌルなので状態異常「ヌルヌル」にならない",
      "ターン終了時に「あなほり」をする事がある",
    ],
    62 => ["盗賊ばびゅーん！",
      "棍を装備可能",
      "「棍技」「盗賊技」を使用可能",
      "素早さと会心率および回避率が少しアップ",
    ],
    64 => ["盗賊プチメイド",
      "皿を装備可能",
      "「料理」「御奉仕」「盗賊技」を使用可能",
      "「御奉仕」の威力が少しアップ",
    ],
    66 => ["盗賊アイテム番",
      "「盗賊技」「商技」を使用可能",
      "アイテムを盗んだり、落としたりする確率が少しアップ",
    ],
    68 => ["盗賊暴れん坊",
      "「盗賊技」を使用可能",
      "瀕死になると勝手に暴れ出す",
      "瀕死になると全能力が大幅にアップし、一部スキルを二連続で発動",
    ],
    70 => ["バイオハザード・ネズミ",
      "通常攻撃がバイオ属性になる",
      "バイオ属性攻撃の威力がアップ",
      "バイオ属性を無効にし、状態異常「毒」にならない",
    ],
    71 => ["バニシングウルフ",
      "会心率・回避率がアップ",
      "「獣技」の威力が少しアップ",
    ],
    72 => ["不死鳥の魂",
      "「獣技」「ブレス」を使用可能",
      "戦闘不能になっても一度だけ体力半分で復活する",
      "炎属性を無効にする",
    ],
    73 => ["ヒル・オブ・ヒル",
      "通常攻撃で拘束する事がある",
      "すでにヌルヌルなので状態異常「ヌルヌル」にならない",
      "「特技」に属する吸精スキルが強化",
    ],
    74 => ["狩人バニー",
      "軽装の防具が装備可能",
      "「弓技」を使用可能",
      "「弓技」の威力がアップ",
      "器用さが30%アップ",
    ],
    75 => ["酒飲み羊",
      "反撃率と会心率がアップ",
      "敵に狙われる確率が少し低い",
      "指示を無視して酒を飲む事がある",
      "酔うと酔拳を発動する",
    ],
    76 => ["ぴちぴちあわあわ",
      "通常攻撃で頻繁にヌルヌルにする",
      "泡を用いたスキルが強化",
      "回避率がアップ",
    ],
    77 => ["レーザーアイ＆シザーズレッグ",
      "通常攻撃でショック状態にする事がある",
      "通常攻撃で拘束する事がある",
    ],
    78 => ["浮遊令嬢",
      "回避率・魔法回避率がアップ",
      "「虫技」に属する吸精スキルが強化",
      "「虫技」に属する吸精スキルの消費SPが半減",
    ],
    79 => ["ふしぎないきもの",
      "通常攻撃で頻繁にヌルヌルにする",
      "「触手技」の威力がアップ",
      "30以下の被ダメージを無効化する",
    ],
    80 => ["オークが町にやってきた！",
      "一般的な防具が装備可能",
      "棍を装備可能",
      "「棍技」を使用可能",
      "市街での戦いに強い",
    ],
    81 => ["毒針ハニー",
      "毒針を用いたスキルが強化",
      "毒針を用いたスキルの消費SPが半減",
    ],
    82 => ["ちゅんちゅんスズメ",
      "「踊る」を使用可能",
      "敵に狙われる確率が少し低い",
      "状態異常「睡眠」にならない",
    ],
    83 => ["スカイダンサー",
      "「踊る」を使用可能",
      "「踊る」の成功率がアップ",
      "「踊る」の消費SPが2/3になる",
    ],
    84 => ["なかよし姉妹",
      "妹の分も合わせて通常攻撃が2回攻撃に",
      "妹の分も合わせて「翼技」が2連続で発動する",
    ],
    85 => ["ヌルヌル令嬢",
      "「尖剣技」「粘液技」を使用可能",
      "通常攻撃で頻繁にヌルヌルにする",
      "すでにヌルヌルなので状態異常「ヌルヌル」にならない",
      "「ドレス」「薄着」が装備でき、おめかし可能",
    ],
    86 => ["ヌルヌルシスター",
      "「白魔法」「粘液技」を使用可能",
      "通常攻撃で頻繁にヌルヌルにする",
      "すでにヌルヌルなので状態異常「ヌルヌル」にならない",
    ],
    87 => ["三匹のヌルヌル",
      "通常攻撃が三回攻撃になる",
      "通常攻撃で頻繁にヌルヌルにする",
      "すでにヌルヌルなので状態異常「ヌルヌル」にならない",
      "「粘液技」が2連続で発動する",
    ],
    88 => ["パンプキンパワー",
      "「黒魔法」の威力が少しアップ",
      "瀕死になるとHP・MP・SPが徐々に回復していく",
    ],
    89 => ["触手の捕食者",
      "「粘液技」「触手技」を使用可能",
      "通常攻撃で「ヌルヌル」「拘束」「消化」にする事がある",
      "溶解液を用いたスキルが強化",
    ],
    90 => ["洞窟の触手蟲",
      "「触手技」を使用可能",
      "状態異常「暗闇」にならない",
      "洞窟での戦いに強い",
    ],
    91 => ["薄命バーニング",
      "炎属性攻撃の威力がアップ",
      "HPが30%以上残っていれば戦闘不能にならずHPが1残る",
    ],
    92 => ["トラップ肉花弁",
      "通常攻撃で拘束・消化する事がある",
      "ターン終了時、頻繁に「捕食」を行う",
    ],
    93 => ["魔獣アポトーシス",
      "「獣技」を使用可能",
      "「獣技」の威力がアップ",
    ],
    94 => ["マルチビットクロー＆拘束装置",
      "通常攻撃が二回攻撃になる",
      "通常攻撃で頻繁に拘束する",
    ],
    95 => ["ダークエルフ剣士",
      "剣・騎士剣を装備可能",
      "「剣技」を使用可能",
      "体力が3/4以下になると、SPが徐々に回復する",
    ],
    96 => ["ダークエルフ蝕魔導師",
      "「黒魔法」「触手技」を使用可能",
      "「触手技」の威力が少しアップ",
      "氷属性攻撃の威力がアップ",
    ],
    97 => ["森の妖精",
      "「自然感応」の威力がアップ",
      "敵に狙われる確率が少し低い",
    ],
    98 => ["あわあわ見習い",
      "通常攻撃で頻繁にヌルヌルにする",
      "泡を用いたスキルが強化",
      "泡を用いたスキルの消費SPが半減",
    ],
    99 => ["電気ナマズ",
      "「自然感応」を使用可能",
      "「自然感応」のダメージが精神力依存になる",
      "雷・土属性攻撃の威力がアップ",
    ],
    100 => ["ラフレシアの魔香",
      "通常攻撃で恍惚にする事がある",
      "花粉を用いたスキルの成功率がアップ",
      "戦闘開始時、「陶酔の芳香」を発動する事がある",
    ],
    101 => ["野良ケンタウロス",
      "槍・重槍を装備可能",
      "「槍技」を使用可能",
      "「槍技」の威力が少しアップ",
    ],
    102 => ["見習い忍者",
      "「忍術」を使用可能",
      "「忍術」の威力がアップ",
      "会心率がアップ",
    ],
    103 => ["見習い陰陽師",
      "「陰陽術」を使用可能",
      "「陰陽術」の威力がアップ",
    ],
    104 => ["時紡ぎ",
      "「時魔法」を使用可能",
      "「時魔法」の成功率が少しアップ",
      "粘糸を用いたスキルの消費SPが半分になる",
    ],
    105 => ["メイド・イン・ミミック",
      "溶解液を用いたスキルが強化",
      "スキル「びっくり箱」の成功率がアップ",
    ],
    106 => ["月下の狂狐",
      "「陰陽術」「獣技」の威力がアップ",
      "体力が半分以下になるとMPが徐々に回復していく",
    ],
    107 => ["夢見るナマコ",
      "通常攻撃で「睡眠」「拘束」にする事がある",
      "状態異常「睡眠」にならない",
      "「特技」に属する吸精スキルが強化",
    ],
    108 => ["貝殻お嫁さん",
      "「料理」「御奉仕」を使用可能",
      "「御奉仕」の消費SPが2/3になる",
      "防御でダメージを1/4に軽減する",
    ],
    109 => ["あわあわマイスター",
      "通常攻撃でヌルヌル・恍惚にする事がある",
      "泡を用いたスキルが大幅に強化",
      "泡を用いたスキルの消費SPが2/3になる",
    ],
    110 => ["肉食スライム",
      "通常攻撃で消化状態にする事がある",
      "「粘液技」の威力がアップ",
    ],
    111 => ["ミラクルスイカ",
      "通常攻撃で眠らせる事がある",
      "「オラクル」を使用可能",
      "蜜を用いた回復技の効果がアップ",
    ],
    112 => ["どろどろウツボカズラ",
      "「粘液技」を使用可能",
      "溶解液を用いたスキルが強化",
    ],
    113 => ["正統ラミア",
      "「蛇技」を使用可能",
      "「蛇技」の威力が少しアップ",
      "「鉄球技」「蛇技」の消費SPが2/3になる",
    ],
    114 => ["わかめ魂",
      "「踊る」「海技」を使用可能",
      "「踊る」の状態異常発生率がアップ",
      "通常攻撃でヌルヌルにする事がある",
    ],
    115 => ["毒針くらげ",
      "通常攻撃で「毒」「麻痺」「拘束」にする事がある",
      "回避率がアップ",
      "触手針を用いたスキルが強化",
    ],
    116 => ["毒針イソギンチャク",
      "通常攻撃で「毒」「麻痺」「拘束」にする事がある",
      "「触手技」が二連続で発動",
      "触手針を用いたスキルが強化",
    ],
    117 => ["不動のアンコウ",
      "暗闇・睡眠・スタンおよび快楽状態異常を無効化する",
      "通常攻撃で拘束する事がある",
    ],
    118 => ["多芸人魚",
      "「白魔法」「歌う」「海技」の威力が少しアップ",
    ],
    119 => ["しびれる書物",
      "通常攻撃で麻痺・ショック状態にする事がある",
      "「魔本術」を使用可能",
      "「魔本術」を使用した際、50%の確率でページを消費しない",
      "回避率・魔法回避率がアップ",
    ],
    120 => ["巨腕ボディーガード",
      "通常攻撃が二回攻撃になる",
      "「格闘」を使用可能",
      "「魔本術」を使用した際、50%の確率でページを消費しない",
      "攻撃力が30%アップ",
    ],
    121 => ["テンタクルディクション",
      "「魔本術」「魔技」「触手技」を使用可能",
      "「魔本術」の威力がアップ",
      "「魔本術」を使用した際、50%の確率でページを消費しない",
    ],
    122 => ["聖者の蛇妖",
      "通常攻撃でスタンさせる事がある",
      "「白魔法」の威力がアップ",
    ],
    123 => ["聖者の淫魔",
      "通常攻撃で敏感・恍惚状態にする事がある",
      "「白魔法」の威力がアップ",
    ],
    124 => ["ペロペロビースト",
      "「魔技」を使用可能",
      "舌を用いたスキルが強化",
      "舌を用いたスキルの消費SPが半減",
    ],
    125 => ["荒ぶる獣性",
      "会心率がアップ",
      "「獣技」の威力がアップ",
    ],
    126 => ["精気吸収システム",
      "「造技」に属する吸収技の威力がアップ",
      "「造技」に属する吸収技の消費SPが半減",
    ],
    127 => ["弱体インセクト",
      "弱体系スキルの威力がアップ",
      "弱体系スキルの消費SPが半減",
    ],
    128 => ["ガンナーキャンサー",
      "「銃技」「造技」を使用可能",
      "「銃技」「造技」の威力が少しアップ",
      "戦闘開始時「フルガトリング」を発動する事がある",
    ],
    129 => ["マシンコマンダー",
      "「銃技」「マキナ」を使用可能",
      "「銃技」「マキナ」の威力がアップ",
      "体に組み込まれた一部の「マキナ」が未所持で使用可能",
    ],
    130 => ["乾きのゴースト",
      "回避率がアップ",
      "「屍技」の威力がアップ",
    ],
    131 => ["髪の伸びる人形",
      "「魔技」を使用可能",
      "髪を用いたスキルが強化",
      "髪を用いたスキルの消費SPが半減",
    ],
    132 => ["疾風のゾンビ剣士",
      "剣・騎士剣を装備可能",
      "「剣技」を使用可能",
      "「剣技」「屍技」の威力が少しアップ",
      "戦闘開始時、「疾風突き」を発動する事がある",
    ],
    133 => ["ゾンビ集団",
      "通常攻撃が「乱れ撃ち」になる",
      "「屍技」が二連続で発動",
    ],
    134 => ["才女なのじゃ！",
      "「召喚」「マキナ」「医術」を使用可能",
      "「召喚」の威力がアップ",
    ],
    135 => ["究極のゾンビ",
      "カウンター攻撃の威力が大幅にアップ",
      "「格闘」「屍技」の威力がアップ",
      "「格闘」の威力が攻撃力にのみ依存する",
    ],
    136 => ["森の番人",
      "「弓技」を使用可能",
      "「弓技」の威力がアップ",
      "「弓技」の消費SPが2/3になる",
    ],
    137 => ["森の職人ズ",
      "通常攻撃が二回攻撃になる",
      "「棍技」が二連続で発動する",
      "敵に狙われる確率が少し低い",
    ],
    138 => ["森の妖精ズ",
      "通常攻撃が二回攻撃になる",
      "「オラクル」が二連続で発動する",
      "敵に狙われる確率が少し低い",
    ],
    139 => ["森の妖精集団",
      "通常攻撃が「乱れ撃ち」になる",
      "「自然感応」が二連続で発動する",
    ],
    140 => ["家事手伝いタランチュラ",
      "「御奉仕」を使用可能",
      "粘糸を用いたスキルが強化",
      "粘糸を用いたスキルの消費SPが半分になる",
    ],
    141 => ["猛牛の斧",
      "斧を装備可能",
      "「斧技」を使用可能",
      "「斧技」の威力がアップ",
    ],
    142 => ["巨腕格闘",
      "「格闘」を使用可能",
      "「格闘」の威力がアップ",
      "「格闘」の威力が攻撃力にのみ依存する",
    ],
    143 => ["器用貧乏淫魔",
      "様々な職業スキルを使用可能",
      "戦闘中、勝手にオラクル技を使用する事がある",
    ],
    144 => ["サボレスフェイズ",
      "「魔技」「虫技」「海賊技」を使用可能",
      "舌を用いたスキルが強化",
      "舌を用いたスキルの消費SPが半分になる",
    ],
    145 => ["甲冑ムカデ",
      "通常攻撃で麻痺・拘束状態にする事がある",
      "防御でダメージを1/4に軽減する",
      "「虫技」の威力が少しアップ",
    ],
    146 => ["甲冑サソリ",
      "通常攻撃で即死させる事がある",
      "防御でダメージを1/4に軽減する",
      "毒針を用いたスキルが強化",
    ],
    147 => ["ちくちくサボテン",
      "針を用いたスキルが強化",
      "針を用いたスキルの消費SPが半減",
      "カウンター率が大幅にアップ",
    ],
    148 => ["格闘ダチョウ",
      "「格闘」を使用可能",
      "「格闘」の威力がアップ",
      "「格闘」の威力が素早さにのみ依存する",
    ],
    149 => ["フォーチュンランプ",
      "「召喚」「オラクル」を使用可能",
      "「召喚」の消費MPが2/3になる",
      "雷属性攻撃の威力がアップ",
    ],
    150 => ["高貴なミイラ",
      "尖剣を装備可能",
      "「尖剣技」を使用可能",
      "「尖剣技」「黒魔法」の威力が少しアップ",
      "包帯を用いたスキルが強化",
    ],
    151 => ["毒牙の蛇妖",
      "通常攻撃で即死させる事がある",
      "「獣技」を使用可能",
      "牙を用いたスキルが強化",
    ],
    152 => ["おしゃべり集団蛇妖",
      "通常攻撃が「乱れ撃ち」になる",
      "「話す」を使用可能",
      "「蛇技」が2連続で発動する",
    ],
    154 => ["アリゲーターファング",
      "通常攻撃で拘束状態にする事がある",
      "牙を用いたスキルが強化",
      "ターン終了時、「捕食」を行う事がある",
    ],
    155 => ["みんなのアイドル",
      "「踊る」「歌う」を使用可能",
      "「踊る」「歌う」の成功率がアップ",
      "敵に狙われる確率が少し低い",
    ],
    156 => ["はずかし剣士",
      "剣・騎士剣を装備可能",
      "「剣技」を使用可能",
      "「剣技」の威力が少しアップ",
      "「剣技」の消費SPが2/3になる",
    ],
    157 => ["土蜘蛛の罠",
      "通常攻撃でヌルヌル・拘束状態にする事がある",
      "粘糸を用いたスキルが強化",
      "粘糸を用いたスキルの消費SPが半分になる",
    ],
    158 => ["ドレインサック",
      "「触手技」に属する吸収スキルが大幅に強化",
      "「触手技」に属するスキルの消費SPが半分になる",
    ],
    159 => ["ナイトメアメイデン",
      "「魔技」を使用可能",
      "通常攻撃で拘束状態にする事がある",
      "「悪夢の抱擁」が大幅に強化",
      "戦闘開始時、「悪夢の抱擁」を発動する事がある",
    ],
    160 => ["アイスメイズ",
      "「触手技」の威力が少しアップ",
      "氷属性攻撃の威力がアップ",
    ],
    161 => ["噛み付きコック",
      "「料理」「獣技」を使用可能",
      "「料理」の効果がアップ",
    ],
    162 => ["蜜と触手",
      "「粘液技」「触手技」を使用可能",
      "「粘液技」「触手技」が二連続で発動",
    ],
    163 => ["マッドメイズ",
      "「召喚」「魔導科学」「触手技」の威力が少しアップ",
    ],
    164 => ["小鬼の棍棒",
      "棍を装備可能",
      "「棍技」を使用可能",
      "「棍技」の威力が少しアップ",
    ],
    165 => ["オナホアシスト",
      "「粘液技」を使用可能",
      "「淫技」に属する手コキ技が大幅に強化",
    ],
    166 => ["看護婦さんです",
      "「医術」を使用可能",
      "「医術」の威力がアップ",
      "敵に狙われる確率がやや低い",
    ],
    167 => ["マッドアルケミスト",
      "「召喚」「錬金術」「触手技」の威力が少しアップ",
    ],
    168 => ["百々魔眼",
      "魔眼スキルが強化され、状態異常発生率が高い",
      "戦闘開始時、ランダムに魔眼を使用する事がある",
    ],
    169 => ["盗賊竜",
      "「短剣技」「盗賊技」を使用可能",
      "戦闘後の獲得ゴールドが少しアップ",
    ],
    170 => ["山賊竜",
      "「剣技」「盗賊技」を使用可能",
      "「剣技」の威力が少しアップ",
      "体力が半分以下になるとスキルの消費SPが半減",
    ],
    171 => ["竜賊王",
      "「剣技」「盗賊技」を使用可能",
      "「剣技」の威力が少しアップ",
      "瀕死になると「剣技」が二連続で発動する",
    ],
    172 => ["熱砂の蜃気楼",
      "「踊る」「淫技」を使用可能",
      "回避率と魔法回避率がアップ",
      "砂漠での戦いに強い",
    ],
    173 => ["熱砂のアリジゴク",
      "通常攻撃で頻繁に拘束状態にする",
      "「虫技」の威力が少しアップ",
      "砂漠での戦いに強い",
    ],
    174 => ["熱砂の巨虫",
      "巨体を活かしたスキルが強化",
      "巨体を活かしたスキルの消費SPが半減",
      "砂漠での戦いに強い",
    ],
    175 => ["熱砂の猛獣使い",
      "「鞭技」「話す」を使用可能",
      "「鞭技」の威力がアップ",
      "砂漠での戦いに強い",
    ],
    176 => ["ヴィタエ・アクア",
      "「粘液技」「造技」を使用可能",
      "「粘液技」の威力がアップ",
      "水属性攻撃の威力がアップ",
    ],
    177 => ["ビッグマウス",
      "「格闘」「獣技」を使用可能",
      "通常攻撃で消化状態にする事がある",
      "牙を用いたスキルが少し強化",
    ],
    178 => ["マキナゲージ",
      "通常攻撃で拘束状態にする事がある",
      "「マキナ」の威力がアップ",
    ],
    179 => ["笑うアルレッキーノ",
      "回避率と魔法回避率および会心率が少しアップ",
      "「歌う」を使用可能",
      "「歌う」の成功率が少しアップ",
    ],
    180 => ["魔導影",
      "回避率と魔法回避率がアップ",
      "鎌を装備可能",
      "「鎌技」「黒魔法」を使用可能",
      "「鎌技」「黒魔法」の威力がアップ",
    ],
    181 => ["語り掛ける芸術",
      "「魔技」「話す」を使用可能",
      "「話す」の成功率がアップ",
    ],
    182 => ["体内錬金",
      "「錬金術」を使用可能",
      "「錬金術」の消費SPを半分にする",
    ],
    183 => ["自律メイデン",
      "「魔技」「触手技」を使用可能",
      "通常攻撃で拘束状態にする事がある",
      "「悪夢の抱擁」が強化",
    ],
    184 => ["ジャンクマインド",
      "通常攻撃が「乱れ撃ち」になる",
      "「造技」が二連続で発動",
    ],
    185 => ["試作型メイドロボ",
      "「御奉仕」を使用可能",
      "「御奉仕」の威力がアップ",
    ],
    525 => ["棍棒娘",
      "棍・杖を装備可能",
      "「棍技」「白魔法」を使用可能",
      "「棍技」「白魔法」の威力がアップ",
    ],
    529 => ["おてんば姫の剛剣",
      "剣・騎士剣を装備可能",
      "「剣技」「王技」を使用可能",
      "「剣技」「王技」の威力がアップ",
    ],
    531 => ["メカニック法王",
      "銃を装備可能",
      "「銃技」「聖技」「マキナ」を使用可能",
      "体に組み込まれた一部の「マキナ」が未所持でも使用可能",
    ],
    533 => ["ウィップクィーン",
      "鞭を装備可能",
      "「鞭技」「王技」を使用可能",
      "「鞭技」「王技」の威力がアップ",
    ],
    540 => ["残念なラミア",
      "敵に狙われる確率が極端に低い",
      "「話す」を使用可能",
      "「話す」の成功率が大幅にアップ",
    ],
    541 => ["残念なハーピー",
      "敵に狙われる確率が極端に低い",
      "回避率および魔法回避率が異常に高い",
    ],
    542 => ["残念なマーメイド",
      "敵に狙われる確率が極端に低い",
      "「商技」の消費ゴールドが1/2になる",
      "まれに突然死する",
    ],
    544 => ["快楽の使徒",
      "通常攻撃で敏感・恍惚状態にする事がある",
      "通常攻撃が快楽属性になる",
      "快楽属性ダメージを半減",
    ],
    545 => ["一般市民",
      "敵に狙われる確率が低い",
      "市街での戦いに強い",
      "瀕死になると回避率が上がる",
    ],
    546 => ["街角のルサンチマン",
      "敵に狙われる確率が低い",
      "受けたダメージに応じて所持金が増える",
    ],
    547 => ["裏社会のダリア",
      "銃を装備可能",
      "「銃技」「商技」を使用可能",
      "「銃技」の威力がアップ",
    ],
    548 => ["ラッキーバニィちゃん",
      "敵に狙われる確率が極端に低い",
      "獲得するゴールドが1.5倍になる",
      "敵が仲間になる確率が1.5倍になる",
    ],
    549 => ["熟練の盗賊",
      "「盗賊技」を使用可能",
      "アイテムを盗んだり、落としたりする確率が少しアップ",
    ],
    550 => ["背水の超気功",
      "「格闘」を使用可能",
      "瀕死になると会心率と回避率が大幅に上がる",
    ],
    551 => ["伝説のメイドの弟子",
      "「御奉仕」を使用可能",
      "「御奉仕」の威力がアップ",
      "瀕死時に勝利すると獲得職業経験値が2倍になる",
    ],
    552 => ["ふわふわエルフ",
      "敵に狙われる確率が低い",
      "「弓技」を使用可能",
      "「弓技」の威力がアップ",
    ],
    553 => ["見習い学者",
      "敵に狙われる確率が低い",
      "「魔導科学」を使用可能",
      "「魔導科学」の威力が少しアップ",
    ],
    554 => ["淫乱ナース",
      "「医術」「淫技」を使用可能",
      "「医術」「淫技」の威力が少しアップ",
    ],
    555 => ["ふわふわソウル",
      "敵に狙われる確率が低い",
      "受けたダメージに応じてMPが回復する",
    ],
    556 => ["貞淑なる僧侶",
      "「白魔法」を使用可能",
      "「白魔法」の消費MPが2/3になる",
    ],
    557 => ["ジャスティスカイザー",
      "敵に狙われる確率が高い",
      "戦闘開始時、変身する事がある",
    ],
    558 => ["街角の占い師",
      "敵に狙われる確率が低い",
      "ターン終了時にタロット占いを行う",
    ],
    559 => ["アサシンの長",
      "敵に狙われる確率が低い",
      "通常攻撃で頻繁に即死させる",
      "「忍術」を使用可能",
    ],
    560 => ["魅惑のダンサー",
      "「踊り」を使用可能",
      "戦闘開始時「セクシーダンス」を踊る事がある",
    ],
    561 => ["貧乳ウィッチ",
      "「黒魔法」を使用可能",
      "瀕死になるとMPが徐々に回復する",
    ],
    562 => ["剛力鍛冶屋",
      "「棍技」を使用可能",
      "瀕死になるとSPが徐々に回復する",
      "通常攻撃時、素材を盗む事がある",
    ],
    563 => ["神殿兵士",
      "瀕死になると被ダメージが軽減",
    ],
    564 => ["イリアの電光",
      "槍・重槍を装備可能",
      "「槍技」を使用可能",
      "瀕死になると「槍技」が二連続で発動する",
    ],
    565 => ["サバサの剛槌",
      "棍を装備可能",
      "「棍技」を使用可能",
      "戦闘開始時、「岩石落とし」を発動する事がある",
    ],
    566 => ["赤いノースリーブ",
      "物理回避率と命中率が異常に高い",
      "戦闘中、ヘタれる事がある",
      "戦闘中、殴られる事がある",
    ],
    567 => ["変態紳士",
      "通常攻撃でパンツを盗む事がある",
      "戦闘開始時にパンツを盗む事がある",
      "ターン終了時にパンツを盗む事がある",
    ],
  }
end

 